#ifndef _CSLR_USB_1_H_
#define _CSLR_USB_1_H_
/*********************************************************************
 * Copyright (C) 2003-2004 Texas Instruments Incorporated.
 * All Rights Reserved
 *********************************************************************/
 /** \file cslr_usb_1.h
 *
 * \brief This file contains the Register Desciptions for USB
 *
 *********************************************************************/

#include <cslr.h>

#include <tistdtypes.h>

/**************************************************************************\
* Register Overlay Structure for Channel
\**************************************************************************/
typedef struct  {
    volatile Uint32 TCPPIDMASTATEW0;
    volatile Uint32 TCPPIDMASTATEW1;
    volatile Uint32 TCPPIDMASTATEW2;
    volatile Uint32 TCPPIDMASTATEW3;
    volatile Uint32 TCPPIDMASTATEW4;
    volatile Uint32 TCPPIDMASTATEW5;
    volatile Uint8 RSVD0[4];
    volatile Uint32 TCPPICOMPPTR;
    volatile Uint32 RCPPIDMASTATEW0;
    volatile Uint32 RCPPIDMASTATEW1;
    volatile Uint32 RCPPIDMASTATEW2;
    volatile Uint32 RCPPIDMASTATEW3;
    volatile Uint32 RCPPIDMASTATEW4;
    volatile Uint32 RCPPIDMASTATEW5;
    volatile Uint32 RCPPIDMASTATEW6;
    volatile Uint32 RCPPICOMPPTR;
} CSL_UsbChannelRegs;

/**************************************************************************\
* Register Overlay Structure for EPTRG
\**************************************************************************/
typedef struct  {
    volatile Uint8 TXFUNCADDR;
    volatile Uint8 RSVD0[1];
    volatile Uint8 TXHUBADDR;
    volatile Uint8 TXHUBPORT;
    volatile Uint8 RXFUNCADDR;
    volatile Uint8 RSVD1[1];
    volatile Uint8 RXHUBADDR;
    volatile Uint8 RXHUBPORT;
} CSL_UsbEptrgRegs;

/**************************************************************************\
* Register Overlay Structure for EPCSR
\**************************************************************************/
typedef struct  {
    volatile Uint16 TXMAXP;
    volatile Uint16 PERI_CSR0;
    volatile Uint16 RXMAXP;
    volatile Uint16 PERI_RXCSR;
    volatile Uint16 COUNT0;
    volatile Uint8 HOST_TYPE0;
    volatile Uint8 HOST_NAKLIMIT0;
    volatile Uint8 HOST_RXTYPE;
    volatile Uint8 HOST_RXINTERVAL;
    volatile Uint8 RSVD0[1];
    volatile Uint8 CONFIGDATA;
} CSL_UsbEpcsrRegs;

/**************************************************************************\
* Register Overlay Structure
\**************************************************************************/
typedef struct  {
    volatile Uint32 REVR;
    volatile Uint32 CTRLR;
    volatile Uint32 STATR;
    volatile Uint32 EMUR;
    volatile Uint32 RNDISR;
    volatile Uint32 AUTOREQ;
    volatile Uint8 RSVD0[8];
    volatile Uint32 INTSRCR;
    volatile Uint32 INTSETR;
    volatile Uint32 INTCLRR;
    volatile Uint32 INTMSKR;
    volatile Uint32 INTMSKSETR;
    volatile Uint32 INTMSKCLRR;
    volatile Uint32 INTMASKEDR;
    volatile Uint32 EOIR;
    volatile Uint32 INTVECTR;
    volatile Uint8 RSVD1[60];
    volatile Uint32 TCPPICR;
    volatile Uint32 TCPPITDR;
    volatile Uint32 TCPPIEOIR;
    volatile Uint32 TCPPIIVECTR;
    volatile Uint32 TCPPIMSKSR;
    volatile Uint32 TCPPIRAWSR;
    volatile Uint32 TCPPIIENSETR;
    volatile Uint32 TCPPIIENCLRR;
    volatile Uint8 RSVD2[32];
    volatile Uint32 RCPPICR;
    volatile Uint8 RSVD3[12];
    volatile Uint32 RCPPIMSKSR;
    volatile Uint32 RCPPIRAWSR;
    volatile Uint32 RCPPIENSETR;
    volatile Uint32 RCPPIIENCLRR;
    volatile Uint32 RBUFCNT0;
    volatile Uint32 RBUFCNT1;
    volatile Uint32 RBUFCNT2;
    volatile Uint32 RBUFCNT3;
    volatile Uint8 RSVD4[16];
    CSL_UsbChannelRegs CHANNEL[4];
    volatile Uint8 RSVD5[512];
    volatile Uint8 FADDR;
    volatile Uint8 POWER;
    volatile Uint16 INTRTX;
    volatile Uint16 INTRRX;
    volatile Uint16 INTRTXE;
    volatile Uint16 INTRRXE;
    volatile Uint8 INTRUSB;
    volatile Uint8 INTRUSBE;
    volatile Uint16 FRAME;
    volatile Uint8 INDEX;
    volatile Uint8 TESTMODE;
    volatile Uint16 TXMAXP;
    volatile Uint16 PERI_CSR0;
    volatile Uint16 RXMAXP;
    volatile Uint16 PERI_RXCSR;
    volatile Uint16 COUNT0;
    volatile Uint8 HOST_TYPE0;
    volatile Uint8 HOST_NAKLIMIT0;
    volatile Uint8 HOST_RXTYPE;
    volatile Uint8 HOST_RXINTERVAL;
    volatile Uint8 RSVD6[1];
    volatile Uint8 CONFIGDATA;
    volatile Uint32 FIFO0;
    volatile Uint32 FIFO1;
    volatile Uint32 FIFO2;
    volatile Uint32 FIFO3;
    volatile Uint32 FIFO4;
    volatile Uint8 RSVD7[44];
    volatile Uint8 DEVCTL;
    volatile Uint8 RSVD8[1];
    volatile Uint8 TXFIFOSZ;
    volatile Uint8 RXFIFOSZ;
    volatile Uint16 TXFIFOADDR;
    volatile Uint16 RXFIFOADDR;
    volatile Uint8 RSVD9[4];
    volatile Uint16 HWVERS;
    volatile Uint8 RSVD10[6];
    volatile Uint8 EPINFO;
    volatile Uint8 RAMINFO;
    volatile Uint8 RSVD11;
    volatile Uint8 VPLEN;
    volatile Uint8 RSVD12[8];
    CSL_UsbEptrgRegs EPTRG[5];
    volatile Uint8 RSVD13[88];
    CSL_UsbEpcsrRegs EPCSR[5];
} CSL_UsbRegs;

  /* Following lines are added due to CSL3.x tools limitations of not
generating the registers with same
  offset address*/
  #define HOST_CSR0 PERI_CSR0
  #define PERI_TXCSR PERI_CSR0
  #define HOST_TXCSR PERI_CSR0
  #define HOST_RXCSR PERI_RXCSR
  #define RXCOUNT COUNT0
  #define HOST_TXTYPE HOST_TYPE0
  #define HOST_TXINTERVAL HOST_NAKLIMIT0
  #define FIFOSIZE CONFIGDATA

/**************************************************************************\
* Field Definition Macros
\**************************************************************************/

/* REVR */

#define CSL_USB_REVR_MODID_MASK          (0x3FFF0000u)
#define CSL_USB_REVR_MODID_SHIFT         (0x00000010u)
#define CSL_USB_REVR_MODID_RESETVAL      (0x00000014u)

#define CSL_USB_REVR_REVRTL_MASK         (0x0000F800u)
#define CSL_USB_REVR_REVRTL_SHIFT        (0x0000000Bu)
#define CSL_USB_REVR_REVRTL_RESETVAL     (0x00000000u)

#define CSL_USB_REVR_REVMAJ_MASK         (0x00000700u)
#define CSL_USB_REVR_REVMAJ_SHIFT        (0x00000008u)
#define CSL_USB_REVR_REVMAJ_RESETVAL     (0x00000001u)

#define CSL_USB_REVR_REVMIN_MASK         (0x000000FFu)
#define CSL_USB_REVR_REVMIN_SHIFT        (0x00000000u)
#define CSL_USB_REVR_REVMIN_RESETVAL     (0x00000000u)

#define CSL_USB_REVR_RESETVAL            (0x00140100u)

/* CTRLR */

#define CSL_USB_CTRLR_RNDIS_MASK         (0x00000010u)
#define CSL_USB_CTRLR_RNDIS_SHIFT        (0x00000004u)
#define CSL_USB_CTRLR_RNDIS_RESETVAL     (0x00000000u)

#define CSL_USB_CTRLR_UINT_MASK          (0x00000008u)
#define CSL_USB_CTRLR_UINT_SHIFT         (0x00000003u)
#define CSL_USB_CTRLR_UINT_RESETVAL      (0x00000000u)

#define CSL_USB_CTRLR_CLKFACK_MASK       (0x00000002u)
#define CSL_USB_CTRLR_CLKFACK_SHIFT      (0x00000001u)
#define CSL_USB_CTRLR_CLKFACK_RESETVAL   (0x00000000u)

#define CSL_USB_CTRLR_RESET_MASK         (0x00000001u)
#define CSL_USB_CTRLR_RESET_SHIFT        (0x00000000u)
#define CSL_USB_CTRLR_RESET_RESETVAL     (0x00000000u)

#define CSL_USB_CTRLR_RESETVAL           (0x00000000u)

/* STATR */

#define CSL_USB_STATR_DRVVBUS_MASK       (0x00000001u)
#define CSL_USB_STATR_DRVVBUS_SHIFT      (0x00000000u)
#define CSL_USB_STATR_DRVVBUS_RESETVAL   (0x00000000u)

#define CSL_USB_STATR_RESETVAL           (0x00000000u)

/* EMUR */

#define CSL_USB_EMUR_RTSEL_MASK          (0x00000004u)
#define CSL_USB_EMUR_RTSEL_SHIFT         (0x00000002u)
#define CSL_USB_EMUR_RTSEL_RESETVAL      (0x00000000u)

#define CSL_USB_EMUR_SOFT_MASK           (0x00000002u)
#define CSL_USB_EMUR_SOFT_SHIFT          (0x00000001u)
#define CSL_USB_EMUR_SOFT_RESETVAL       (0x00000001u)

#define CSL_USB_EMUR_FREERUN_MASK        (0x00000001u)
#define CSL_USB_EMUR_FREERUN_SHIFT       (0x00000000u)
#define CSL_USB_EMUR_FREERUN_RESETVAL    (0x00000001u)

#define CSL_USB_EMUR_RESETVAL            (0x00000003u)

/* RNDISR */

#define CSL_USB_RNDISR_RX4EN_MASK        (0x00080000u)
#define CSL_USB_RNDISR_RX4EN_SHIFT       (0x00000013u)
#define CSL_USB_RNDISR_RX4EN_RESETVAL    (0x00000000u)

#define CSL_USB_RNDISR_RX3EN_MASK        (0x00040000u)
#define CSL_USB_RNDISR_RX3EN_SHIFT       (0x00000012u)
#define CSL_USB_RNDISR_RX3EN_RESETVAL    (0x00000000u)

#define CSL_USB_RNDISR_RX2EN_MASK        (0x00020000u)
#define CSL_USB_RNDISR_RX2EN_SHIFT       (0x00000011u)
#define CSL_USB_RNDISR_RX2EN_RESETVAL    (0x00000000u)

#define CSL_USB_RNDISR_RX1EN_MASK        (0x00010000u)
#define CSL_USB_RNDISR_RX1EN_SHIFT       (0x00000010u)
#define CSL_USB_RNDISR_RX1EN_RESETVAL    (0x00000000u)

#define CSL_USB_RNDISR_TX4EN_MASK        (0x00000008u)
#define CSL_USB_RNDISR_TX4EN_SHIFT       (0x00000003u)
#define CSL_USB_RNDISR_TX4EN_RESETVAL    (0x00000000u)

#define CSL_USB_RNDISR_TX3EN_MASK        (0x00000004u)
#define CSL_USB_RNDISR_TX3EN_SHIFT       (0x00000002u)
#define CSL_USB_RNDISR_TX3EN_RESETVAL    (0x00000000u)

#define CSL_USB_RNDISR_TX2EN_MASK        (0x00000002u)
#define CSL_USB_RNDISR_TX2EN_SHIFT       (0x00000001u)
#define CSL_USB_RNDISR_TX2EN_RESETVAL    (0x00000000u)

#define CSL_USB_RNDISR_TX1EN_MASK        (0x00000001u)
#define CSL_USB_RNDISR_TX1EN_SHIFT       (0x00000000u)
#define CSL_USB_RNDISR_TX1EN_RESETVAL    (0x00000000u)

#define CSL_USB_RNDISR_RESETVAL          (0x00000000u)

/* AUTOREQ */

#define CSL_USB_AUTOREQ_RX4_AUTOREQ_MASK (0x000000C0u)
#define CSL_USB_AUTOREQ_RX4_AUTOREQ_SHIFT (0x00000006u)
#define CSL_USB_AUTOREQ_RX4_AUTOREQ_RESETVAL (0x00000000u)

#define CSL_USB_AUTOREQ_RX3_AUTOREQ_MASK (0x00000030u)
#define CSL_USB_AUTOREQ_RX3_AUTOREQ_SHIFT (0x00000004u)
#define CSL_USB_AUTOREQ_RX3_AUTOREQ_RESETVAL (0x00000000u)

#define CSL_USB_AUTOREQ_RX2_AUTOREQ_MASK (0x0000000Cu)
#define CSL_USB_AUTOREQ_RX2_AUTOREQ_SHIFT (0x00000002u)
#define CSL_USB_AUTOREQ_RX2_AUTOREQ_RESETVAL (0x00000000u)

#define CSL_USB_AUTOREQ_RX1_AUTOREQ_MASK (0x00000003u)
#define CSL_USB_AUTOREQ_RX1_AUTOREQ_SHIFT (0x00000000u)
#define CSL_USB_AUTOREQ_RX1_AUTOREQ_RESETVAL (0x00000000u)

#define CSL_USB_AUTOREQ_RESETVAL         (0x00000000u)

/* INTSRCR */

#define CSL_USB_INTSRCR_USB_MASK         (0x01FF0000u)
#define CSL_USB_INTSRCR_USB_SHIFT        (0x00000010u)
#define CSL_USB_INTSRCR_USB_RESETVAL     (0x00000000u)

#define CSL_USB_INTSRCR_RX_MASK          (0x00001F00u)
#define CSL_USB_INTSRCR_RX_SHIFT         (0x00000008u)
#define CSL_USB_INTSRCR_RX_RESETVAL      (0x00000000u)

#define CSL_USB_INTSRCR_TX_MASK          (0x0000001Fu)
#define CSL_USB_INTSRCR_TX_SHIFT         (0x00000000u)
#define CSL_USB_INTSRCR_TX_RESETVAL      (0x00000000u)

#define CSL_USB_INTSRCR_RESETVAL         (0x00000000u)

/* INTSETR */

#define CSL_USB_INTSETR_USB_MASK         (0x01FF0000u)
#define CSL_USB_INTSETR_USB_SHIFT        (0x00000010u)
#define CSL_USB_INTSETR_USB_RESETVAL     (0x00000000u)

#define CSL_USB_INTSETR_RX_MASK          (0x00001F00u)
#define CSL_USB_INTSETR_RX_SHIFT         (0x00000008u)
#define CSL_USB_INTSETR_RX_RESETVAL      (0x00000000u)

#define CSL_USB_INTSETR_TX_MASK          (0x0000001Fu)
#define CSL_USB_INTSETR_TX_SHIFT         (0x00000000u)
#define CSL_USB_INTSETR_TX_RESETVAL      (0x00000000u)

#define CSL_USB_INTSETR_RESETVAL         (0x00000000u)

/* INTCLRR */

#define CSL_USB_INTCLRR_USB_MASK         (0x01FF0000u)
#define CSL_USB_INTCLRR_USB_SHIFT        (0x00000010u)
#define CSL_USB_INTCLRR_USB_RESETVAL     (0x00000000u)

#define CSL_USB_INTCLRR_RX_MASK          (0x00001F00u)
#define CSL_USB_INTCLRR_RX_SHIFT         (0x00000008u)
#define CSL_USB_INTCLRR_RX_RESETVAL      (0x00000000u)

#define CSL_USB_INTCLRR_TX_MASK          (0x0000001Fu)
#define CSL_USB_INTCLRR_TX_SHIFT         (0x00000000u)
#define CSL_USB_INTCLRR_TX_RESETVAL      (0x00000000u)

#define CSL_USB_INTCLRR_RESETVAL         (0x00000000u)

/* INTMSKR */

#define CSL_USB_INTMSKR_USB_MASK         (0x01FF0000u)
#define CSL_USB_INTMSKR_USB_SHIFT        (0x00000010u)
#define CSL_USB_INTMSKR_USB_RESETVAL     (0x00000000u)

#define CSL_USB_INTMSKR_RX_MASK          (0x00001F00u)
#define CSL_USB_INTMSKR_RX_SHIFT         (0x00000008u)
#define CSL_USB_INTMSKR_RX_RESETVAL      (0x00000000u)

#define CSL_USB_INTMSKR_TX_MASK          (0x0000001Fu)
#define CSL_USB_INTMSKR_TX_SHIFT         (0x00000000u)
#define CSL_USB_INTMSKR_TX_RESETVAL      (0x00000000u)

#define CSL_USB_INTMSKR_RESETVAL         (0x00000000u)

/* INTMSKSETR */

#define CSL_USB_INTMSKSETR_USB_MASK      (0x01FF0000u)
#define CSL_USB_INTMSKSETR_USB_SHIFT     (0x00000010u)
#define CSL_USB_INTMSKSETR_USB_RESETVAL  (0x00000000u)

#define CSL_USB_INTMSKSETR_RX_MASK       (0x00001F00u)
#define CSL_USB_INTMSKSETR_RX_SHIFT      (0x00000008u)
#define CSL_USB_INTMSKSETR_RX_RESETVAL   (0x00000000u)

#define CSL_USB_INTMSKSETR_TX_MASK       (0x0000001Fu)
#define CSL_USB_INTMSKSETR_TX_SHIFT      (0x00000000u)
#define CSL_USB_INTMSKSETR_TX_RESETVAL   (0x00000000u)

#define CSL_USB_INTMSKSETR_RESETVAL      (0x00000000u)

/* INTMSKCLRR */

#define CSL_USB_INTMSKCLRR_USB_MASK      (0x01FF0000u)
#define CSL_USB_INTMSKCLRR_USB_SHIFT     (0x00000010u)
#define CSL_USB_INTMSKCLRR_USB_RESETVAL  (0x00000000u)

#define CSL_USB_INTMSKCLRR_RX_MASK       (0x00001F00u)
#define CSL_USB_INTMSKCLRR_RX_SHIFT      (0x00000008u)
#define CSL_USB_INTMSKCLRR_RX_RESETVAL   (0x00000000u)

#define CSL_USB_INTMSKCLRR_TX_MASK       (0x0000001Fu)
#define CSL_USB_INTMSKCLRR_TX_SHIFT      (0x00000000u)
#define CSL_USB_INTMSKCLRR_TX_RESETVAL   (0x00000000u)

#define CSL_USB_INTMSKCLRR_RESETVAL      (0x00000000u)

/* INTMASKEDR */

#define CSL_USB_INTMASKEDR_USB_MASK      (0x01FF0000u)
#define CSL_USB_INTMASKEDR_USB_SHIFT     (0x00000010u)
#define CSL_USB_INTMASKEDR_USB_RESETVAL  (0x00000000u)

#define CSL_USB_INTMASKEDR_RX_MASK       (0x00001F00u)
#define CSL_USB_INTMASKEDR_RX_SHIFT      (0x00000008u)
#define CSL_USB_INTMASKEDR_RX_RESETVAL   (0x00000000u)

#define CSL_USB_INTMASKEDR_TX_MASK       (0x0000001Fu)
#define CSL_USB_INTMASKEDR_TX_SHIFT      (0x00000000u)
#define CSL_USB_INTMASKEDR_TX_RESETVAL   (0x00000000u)

#define CSL_USB_INTMASKEDR_RESETVAL      (0x00000000u)

/* EOIR */

#define CSL_USB_EOIR_VECTOR_MASK         (0x000000FFu)
#define CSL_USB_EOIR_VECTOR_SHIFT        (0x00000000u)
#define CSL_USB_EOIR_VECTOR_RESETVAL     (0x00000000u)

#define CSL_USB_EOIR_RESETVAL            (0x00000000u)

/* INTVECTR */

#define CSL_USB_INTVECTR_VECTOR_MASK     (0xFFFFFFFFu)
#define CSL_USB_INTVECTR_VECTOR_SHIFT    (0x00000000u)
#define CSL_USB_INTVECTR_VECTOR_RESETVAL (0x00000000u)

#define CSL_USB_INTVECTR_RESETVAL        (0x00000000u)

/* TCPPICR */

#define CSL_USB_TCPPICR_TCPPI_ENABLE_MASK (0x00000001u)
#define CSL_USB_TCPPICR_TCPPI_ENABLE_SHIFT (0x00000000u)
#define CSL_USB_TCPPICR_TCPPI_ENABLE_RESETVAL (0x00000000u)

#define CSL_USB_TCPPICR_RESETVAL         (0x00000000u)

/* TCPPITDR */

#define CSL_USB_TCPPITDR_READY_MASK      (0x80000000u)
#define CSL_USB_TCPPITDR_READY_SHIFT     (0x0000001Fu)
#define CSL_USB_TCPPITDR_READY_RESETVAL  (0x00000001u)

#define CSL_USB_TCPPITDR_CHANNEL_MASK    (0x00000003u)
#define CSL_USB_TCPPITDR_CHANNEL_SHIFT   (0x00000000u)
#define CSL_USB_TCPPITDR_CHANNEL_RESETVAL (0x00000000u)

#define CSL_USB_TCPPITDR_RESETVAL        (0x80000000u)

/* TCPPIEOIR */

#define CSL_USB_TCPPIEOIR_VECTOR_MASK    (0x000000FFu)
#define CSL_USB_TCPPIEOIR_VECTOR_SHIFT   (0x00000000u)
#define CSL_USB_TCPPIEOIR_VECTOR_RESETVAL (0x00000000u)

#define CSL_USB_TCPPIEOIR_RESETVAL       (0x00000000u)

/* TCPPIIVECTR */

#define CSL_USB_TCPPIIVECTR_VECTOR_MASK  (0xFFFFFFFFu)
#define CSL_USB_TCPPIIVECTR_VECTOR_SHIFT (0x00000000u)
#define CSL_USB_TCPPIIVECTR_VECTOR_RESETVAL (0x00000000u)

#define CSL_USB_TCPPIIVECTR_RESETVAL     (0x00000000u)

/* TCPPIMSKSR */

#define CSL_USB_TCPPIMSKSR_COMP_PENDING_MASK (0x0000000Fu)
#define CSL_USB_TCPPIMSKSR_COMP_PENDING_SHIFT (0x00000000u)
#define CSL_USB_TCPPIMSKSR_COMP_PENDING_RESETVAL (0x00000000u)

#define CSL_USB_TCPPIMSKSR_RESETVAL      (0x00000000u)

/* TCPPIRAWSR */

#define CSL_USB_TCPPIRAWSR_COMP_PENDING_MASK (0x0000000Fu)
#define CSL_USB_TCPPIRAWSR_COMP_PENDING_SHIFT (0x00000000u)
#define CSL_USB_TCPPIRAWSR_COMP_PENDING_RESETVAL (0x00000000u)

#define CSL_USB_TCPPIRAWSR_RESETVAL      (0x00000000u)

/* TCPPIIENSETR */

#define CSL_USB_TCPPIIENSETR_COMP_PENDING_INTR_EN_MASK (0x0000000Fu)
#define CSL_USB_TCPPIIENSETR_COMP_PENDING_INTR_EN_SHIFT (0x00000000u)
#define CSL_USB_TCPPIIENSETR_COMP_PENDING_INTR_EN_RESETVAL (0x00000000u)

#define CSL_USB_TCPPIIENSETR_RESETVAL    (0x00000000u)

/* TCPPIIENCLRR */

#define CSL_USB_TCPPIIENCLRR_COMP_PENDING_INTR_EN_MASK (0x0000000Fu)
#define CSL_USB_TCPPIIENCLRR_COMP_PENDING_INTR_EN_SHIFT (0x00000000u)
#define CSL_USB_TCPPIIENCLRR_COMP_PENDING_INTR_EN_RESETVAL (0x00000000u)

#define CSL_USB_TCPPIIENCLRR_RESETVAL    (0x00000000u)

/* RCPPICR */

#define CSL_USB_RCPPICR_RCPPI_ENABLE_MASK (0x00000001u)
#define CSL_USB_RCPPICR_RCPPI_ENABLE_SHIFT (0x00000000u)
#define CSL_USB_RCPPICR_RCPPI_ENABLE_RESETVAL (0x00000000u)

#define CSL_USB_RCPPICR_RESETVAL         (0x00000000u)

/* RCPPIMSKSR */

#define CSL_USB_RCPPIMSKSR_MASKED_COMP_PENDING_MASK (0x0000000Fu)
#define CSL_USB_RCPPIMSKSR_MASKED_COMP_PENDING_SHIFT (0x00000000u)
#define CSL_USB_RCPPIMSKSR_MASKED_COMP_PENDING_RESETVAL (0x00000000u)

#define CSL_USB_RCPPIMSKSR_RESETVAL      (0x00000000u)

/* RCPPIRAWSR */

#define CSL_USB_RCPPIRAWSR_COMP_PENDING_MASK (0x0000000Fu)
#define CSL_USB_RCPPIRAWSR_COMP_PENDING_SHIFT (0x00000000u)
#define CSL_USB_RCPPIRAWSR_COMP_PENDING_RESETVAL (0x00000000u)

#define CSL_USB_RCPPIRAWSR_RESETVAL      (0x00000000u)

/* RCPPIENSETR */

#define CSL_USB_RCPPIENSETR_COMP_PENDING_INTR_EN_MASK (0x0000000Fu)
#define CSL_USB_RCPPIENSETR_COMP_PENDING_INTR_EN_SHIFT (0x00000000u)
#define CSL_USB_RCPPIENSETR_COMP_PENDING_INTR_EN_RESETVAL (0x00000000u)

#define CSL_USB_RCPPIENSETR_RESETVAL     (0x00000000u)

/* RCPPIIENCLRR */

#define CSL_USB_RCPPIIENCLRR_COMP_PENDING_INTR_EN_MASK (0x0000000Fu)
#define CSL_USB_RCPPIIENCLRR_COMP_PENDING_INTR_EN_SHIFT (0x00000000u)
#define CSL_USB_RCPPIIENCLRR_COMP_PENDING_INTR_EN_RESETVAL (0x00000000u)

#define CSL_USB_RCPPIIENCLRR_RESETVAL    (0x00000000u)

/* RBUFCNT0 */

#define CSL_USB_RBUFCNT0_BUFCNT_MASK     (0x0000FFFFu)
#define CSL_USB_RBUFCNT0_BUFCNT_SHIFT    (0x00000000u)
#define CSL_USB_RBUFCNT0_BUFCNT_RESETVAL (0x00000000u)

#define CSL_USB_RBUFCNT0_RESETVAL        (0x00000000u)

/* RBUFCNT1 */

#define CSL_USB_RBUFCNT1_BUFCNT_MASK     (0x0000FFFFu)
#define CSL_USB_RBUFCNT1_BUFCNT_SHIFT    (0x00000000u)
#define CSL_USB_RBUFCNT1_BUFCNT_RESETVAL (0x00000000u)

#define CSL_USB_RBUFCNT1_RESETVAL        (0x00000000u)

/* RBUFCNT2 */

#define CSL_USB_RBUFCNT2_BUFCNT_MASK     (0x0000FFFFu)
#define CSL_USB_RBUFCNT2_BUFCNT_SHIFT    (0x00000000u)
#define CSL_USB_RBUFCNT2_BUFCNT_RESETVAL (0x00000000u)

#define CSL_USB_RBUFCNT2_RESETVAL        (0x00000000u)

/* RBUFCNT3 */

#define CSL_USB_RBUFCNT3_BUFCNT_MASK     (0x0000FFFFu)
#define CSL_USB_RBUFCNT3_BUFCNT_SHIFT    (0x00000000u)
#define CSL_USB_RBUFCNT3_BUFCNT_RESETVAL (0x00000000u)

#define CSL_USB_RBUFCNT3_RESETVAL        (0x00000000u)

/* TCPPIDMASTATEW0 */

#define CSL_USB_TCPPIDMASTATEW0_TXQ_HEAD_PTR_MASK (0xFFFFFFFCu)
#define CSL_USB_TCPPIDMASTATEW0_TXQ_HEAD_PTR_SHIFT (0x00000002u)
#define CSL_USB_TCPPIDMASTATEW0_TXQ_HEAD_PTR_RESETVAL (0x00000000u)

#define CSL_USB_TCPPIDMASTATEW0_IN_PACKET_MASK (0x00000001u)
#define CSL_USB_TCPPIDMASTATEW0_IN_PACKET_SHIFT (0x00000000u)
#define CSL_USB_TCPPIDMASTATEW0_IN_PACKET_RESETVAL (0x00000000u)

#define CSL_USB_TCPPIDMASTATEW0_RESETVAL (0x00000000u)

/* TCPPIDMASTATEW1 */

#define CSL_USB_TCPPIDMASTATEW1_SOP_DESCRIPTOR_PTR_MASK (0xFFFFFFFCu)
#define CSL_USB_TCPPIDMASTATEW1_SOP_DESCRIPTOR_PTR_SHIFT (0x00000002u)
#define CSL_USB_TCPPIDMASTATEW1_SOP_DESCRIPTOR_PTR_RESETVAL (0x00000000u)

#define CSL_USB_TCPPIDMASTATEW1_IN_PACKET_MASK (0x00000001u)
#define CSL_USB_TCPPIDMASTATEW1_IN_PACKET_SHIFT (0x00000000u)
#define CSL_USB_TCPPIDMASTATEW1_IN_PACKET_RESETVAL (0x00000000u)

#define CSL_USB_TCPPIDMASTATEW1_RESETVAL (0x00000000u)

/* TCPPIDMASTATEW2 */

#define CSL_USB_TCPPIDMASTATEW2_CURR_DESCRIPTOR_PTR_MASK (0xFFFFFFFCu)
#define CSL_USB_TCPPIDMASTATEW2_CURR_DESCRIPTOR_PTR_SHIFT (0x00000002u)
#define CSL_USB_TCPPIDMASTATEW2_CURR_DESCRIPTOR_PTR_RESETVAL (0x00000000u)

#define CSL_USB_TCPPIDMASTATEW2_TRUNCATED_NON_EOP_MASK (0x00000002u)
#define CSL_USB_TCPPIDMASTATEW2_TRUNCATED_NON_EOP_SHIFT (0x00000001u)
#define CSL_USB_TCPPIDMASTATEW2_TRUNCATED_NON_EOP_RESETVAL (0x00000000u)

#define CSL_USB_TCPPIDMASTATEW2_RESETVAL (0x00000000u)

/* TCPPIDMASTATEW3 */

#define CSL_USB_TCPPIDMASTATEW3_CURR_BUFFER_PTR_MASK (0xFFFFFFFFu)
#define CSL_USB_TCPPIDMASTATEW3_CURR_BUFFER_PTR_SHIFT (0x00000000u)
#define CSL_USB_TCPPIDMASTATEW3_CURR_BUFFER_PTR_RESETVAL (0x00000000u)

#define CSL_USB_TCPPIDMASTATEW3_RESETVAL (0x00000000u)

/* TCPPIDMASTATEW4 */

#define CSL_USB_TCPPIDMASTATEW4_DESC_MSG_MASK (0xFF000000u)
#define CSL_USB_TCPPIDMASTATEW4_DESC_MSG_SHIFT (0x00000018u)
#define CSL_USB_TCPPIDMASTATEW4_DESC_MSG_RESETVAL (0x00000000u)

#define CSL_USB_TCPPIDMASTATEW4_CURR_BUFFER_EOP_MASK (0x00020000u)
#define CSL_USB_TCPPIDMASTATEW4_CURR_BUFFER_EOP_SHIFT (0x00000011u)
#define CSL_USB_TCPPIDMASTATEW4_CURR_BUFFER_EOP_RESETVAL (0x00000000u)

#define CSL_USB_TCPPIDMASTATEW4_CURR_BUFFER_SOP_MASK (0x00010000u)
#define CSL_USB_TCPPIDMASTATEW4_CURR_BUFFER_SOP_SHIFT (0x00000010u)
#define CSL_USB_TCPPIDMASTATEW4_CURR_BUFFER_SOP_RESETVAL (0x00000000u)

#define CSL_USB_TCPPIDMASTATEW4_CURR_BUFFER_LENGTH_MASK (0x0000FFFFu)
#define CSL_USB_TCPPIDMASTATEW4_CURR_BUFFER_LENGTH_SHIFT (0x00000000u)
#define CSL_USB_TCPPIDMASTATEW4_CURR_BUFFER_LENGTH_RESETVAL (0x00000000u)

#define CSL_USB_TCPPIDMASTATEW4_RESETVAL (0x00000000u)

/* TCPPIDMASTATEW5 */

#define CSL_USB_TCPPIDMASTATEW5_REM_LENGTH_MASK (0xFFFF0000u)
#define CSL_USB_TCPPIDMASTATEW5_REM_LENGTH_SHIFT (0x00000010u)
#define CSL_USB_TCPPIDMASTATEW5_REM_LENGTH_RESETVAL (0x00000000u)

#define CSL_USB_TCPPIDMASTATEW5_LENGTH_MASK (0x0000FFFFu)
#define CSL_USB_TCPPIDMASTATEW5_LENGTH_SHIFT (0x00000000u)
#define CSL_USB_TCPPIDMASTATEW5_LENGTH_RESETVAL (0x00000000u)

#define CSL_USB_TCPPIDMASTATEW5_RESETVAL (0x00000000u)

/* TCPPICOMPPTR */

#define CSL_USB_TCPPICOMPPTR_DESC_ADDR_MASK (0xFFFFFFFCu)
#define CSL_USB_TCPPICOMPPTR_DESC_ADDR_SHIFT (0x00000002u)
#define CSL_USB_TCPPICOMPPTR_DESC_ADDR_RESETVAL (0x00000000u)

#define CSL_USB_TCPPICOMPPTR_WRBK_MODE_MASK (0x00000001u)
#define CSL_USB_TCPPICOMPPTR_WRBK_MODE_SHIFT (0x00000000u)
#define CSL_USB_TCPPICOMPPTR_WRBK_MODE_RESETVAL (0x00000000u)

#define CSL_USB_TCPPICOMPPTR_RESETVAL    (0x00000000u)

/* RCPPIDMASTATEW0 */

#define CSL_USB_RCPPIDMASTATEW0_SOP_BUFFER_OFFSET_MASK (0x000000FFu)
#define CSL_USB_RCPPIDMASTATEW0_SOP_BUFFER_OFFSET_SHIFT (0x00000000u)
#define CSL_USB_RCPPIDMASTATEW0_SOP_BUFFER_OFFSET_RESETVAL (0x00000000u)

#define CSL_USB_RCPPIDMASTATEW0_RESETVAL (0x00000000u)

/* RCPPIDMASTATEW1 */

#define CSL_USB_RCPPIDMASTATEW1_RXQ_HEAD_PTR_MASK (0xFFFFFFFCu)
#define CSL_USB_RCPPIDMASTATEW1_RXQ_HEAD_PTR_SHIFT (0x00000002u)
#define CSL_USB_RCPPIDMASTATEW1_RXQ_HEAD_PTR_RESETVAL (0x00000000u)

#define CSL_USB_RCPPIDMASTATEW1_RESETVAL (0x00000000u)

/* RCPPIDMASTATEW2 */

#define CSL_USB_RCPPIDMASTATEW2_SOP_DESCRIPTOR_PTR_MASK (0xFFFFFFFCu)
#define CSL_USB_RCPPIDMASTATEW2_SOP_DESCRIPTOR_PTR_SHIFT (0x00000002u)
#define CSL_USB_RCPPIDMASTATEW2_SOP_DESCRIPTOR_PTR_RESETVAL (0x00000000u)

#define CSL_USB_RCPPIDMASTATEW2_IN_PACKET_MASK (0x00000001u)
#define CSL_USB_RCPPIDMASTATEW2_IN_PACKET_SHIFT (0x00000000u)
#define CSL_USB_RCPPIDMASTATEW2_IN_PACKET_RESETVAL (0x00000000u)

#define CSL_USB_RCPPIDMASTATEW2_RESETVAL (0x00000000u)

/* RCPPIDMASTATEW3 */

#define CSL_USB_RCPPIDMASTATEW3_CURR_DESCRIPTOR_PTR_MASK (0xFFFFFFFCu)
#define CSL_USB_RCPPIDMASTATEW3_CURR_DESCRIPTOR_PTR_SHIFT (0x00000002u)
#define CSL_USB_RCPPIDMASTATEW3_CURR_DESCRIPTOR_PTR_RESETVAL (0x00000000u)

#define CSL_USB_RCPPIDMASTATEW3_RESETVAL (0x00000000u)

/* RCPPIDMASTATEW4 */

#define CSL_USB_RCPPIDMASTATEW4_CURR_BUFFER_PTR_MASK (0xFFFFFFFFu)
#define CSL_USB_RCPPIDMASTATEW4_CURR_BUFFER_PTR_SHIFT (0x00000000u)
#define CSL_USB_RCPPIDMASTATEW4_CURR_BUFFER_PTR_RESETVAL (0x00000000u)

#define CSL_USB_RCPPIDMASTATEW4_RESETVAL (0x00000000u)

/* RCPPIDMASTATEW5 */

#define CSL_USB_RCPPIDMASTATEW5_PKT_LENGTH_MASK (0xFFFF0000u)
#define CSL_USB_RCPPIDMASTATEW5_PKT_LENGTH_SHIFT (0x00000010u)
#define CSL_USB_RCPPIDMASTATEW5_PKT_LENGTH_RESETVAL (0x00000000u)

#define CSL_USB_RCPPIDMASTATEW5_CURR_BUFFER_LENGTH_MASK (0x0000FFFFu)
#define CSL_USB_RCPPIDMASTATEW5_CURR_BUFFER_LENGTH_SHIFT (0x00000000u)
#define CSL_USB_RCPPIDMASTATEW5_CURR_BUFFER_LENGTH_RESETVAL (0x00000000u)

#define CSL_USB_RCPPIDMASTATEW5_RESETVAL (0x00000000u)

/* RCPPIDMASTATEW6 */

#define CSL_USB_RCPPIDMASTATEW6_SOP_BUFFER_BYTECNT_MASK (0xFFFF0000u)
#define CSL_USB_RCPPIDMASTATEW6_SOP_BUFFER_BYTECNT_SHIFT (0x00000010u)
#define CSL_USB_RCPPIDMASTATEW6_SOP_BUFFER_BYTECNT_RESETVAL (0x00000000u)

#define CSL_USB_RCPPIDMASTATEW6_CURR_BUFFER_BYTECNT_MASK (0x0000FFFFu)
#define CSL_USB_RCPPIDMASTATEW6_CURR_BUFFER_BYTECNT_SHIFT (0x00000000u)
#define CSL_USB_RCPPIDMASTATEW6_CURR_BUFFER_BYTECNT_RESETVAL (0x00000000u)

#define CSL_USB_RCPPIDMASTATEW6_RESETVAL (0x00000000u)

/* RCPPICOMPPTR */

#define CSL_USB_RCPPICOMPPTR_DESC_ADDR_MASK (0xFFFFFFFCu)
#define CSL_USB_RCPPICOMPPTR_DESC_ADDR_SHIFT (0x00000002u)
#define CSL_USB_RCPPICOMPPTR_DESC_ADDR_RESETVAL (0x00000000u)

#define CSL_USB_RCPPICOMPPTR_RDBK_MODE_MASK (0x00000001u)
#define CSL_USB_RCPPICOMPPTR_RDBK_MODE_SHIFT (0x00000000u)
#define CSL_USB_RCPPICOMPPTR_RDBK_MODE_RESETVAL (0x00000000u)

#define CSL_USB_RCPPICOMPPTR_RESETVAL    (0x00000000u)

/* FADDR */

#define CSL_USB_FADDR_FUNCADDR_MASK      (0x7Fu)
#define CSL_USB_FADDR_FUNCADDR_SHIFT     (0x00u)
#define CSL_USB_FADDR_FUNCADDR_RESETVAL  (0x00u)

#define CSL_USB_FADDR_RESETVAL           (0x00u)

/* POWER */

#define CSL_USB_POWER_ISOUPDATE_MASK     (0x80u)
#define CSL_USB_POWER_ISOUPDATE_SHIFT    (0x07u)
#define CSL_USB_POWER_ISOUPDATE_RESETVAL (0x00u)

#define CSL_USB_POWER_SOFTCONN_MASK      (0x40u)
#define CSL_USB_POWER_SOFTCONN_SHIFT     (0x06u)
#define CSL_USB_POWER_SOFTCONN_RESETVAL  (0x00u)

#define CSL_USB_POWER_HSEN_MASK          (0x20u)
#define CSL_USB_POWER_HSEN_SHIFT         (0x05u)
#define CSL_USB_POWER_HSEN_RESETVAL      (0x01u)

#define CSL_USB_POWER_HSMODE_MASK        (0x10u)
#define CSL_USB_POWER_HSMODE_SHIFT       (0x04u)
#define CSL_USB_POWER_HSMODE_RESETVAL    (0x00u)

#define CSL_USB_POWER_RESET_MASK         (0x08u)
#define CSL_USB_POWER_RESET_SHIFT        (0x03u)
#define CSL_USB_POWER_RESET_RESETVAL     (0x00u)

#define CSL_USB_POWER_RESUME_MASK        (0x04u)
#define CSL_USB_POWER_RESUME_SHIFT       (0x02u)
#define CSL_USB_POWER_RESUME_RESETVAL    (0x00u)

#define CSL_USB_POWER_SUSPENDM_MASK      (0x02u)
#define CSL_USB_POWER_SUSPENDM_SHIFT     (0x01u)
#define CSL_USB_POWER_SUSPENDM_RESETVAL  (0x00u)

#define CSL_USB_POWER_ENSUSPM_MASK       (0x01u)
#define CSL_USB_POWER_ENSUSPM_SHIFT      (0x00u)
#define CSL_USB_POWER_ENSUSPM_RESETVAL   (0x00u)

#define CSL_USB_POWER_RESETVAL           (0x20u)

/* INTRTX */

#define CSL_USB_INTRTX_EP4TX_MASK        (0x0010u)
#define CSL_USB_INTRTX_EP4TX_SHIFT       (0x0004u)
#define CSL_USB_INTRTX_EP4TX_RESETVAL    (0x0000u)

#define CSL_USB_INTRTX_EP3TX_MASK        (0x0008u)
#define CSL_USB_INTRTX_EP3TX_SHIFT       (0x0003u)
#define CSL_USB_INTRTX_EP3TX_RESETVAL    (0x0000u)

#define CSL_USB_INTRTX_EP2TX_MASK        (0x0004u)
#define CSL_USB_INTRTX_EP2TX_SHIFT       (0x0002u)
#define CSL_USB_INTRTX_EP2TX_RESETVAL    (0x0000u)

#define CSL_USB_INTRTX_EP1TX_MASK        (0x0002u)
#define CSL_USB_INTRTX_EP1TX_SHIFT       (0x0001u)
#define CSL_USB_INTRTX_EP1TX_RESETVAL    (0x0000u)

#define CSL_USB_INTRTX_EP0_MASK          (0x0001u)
#define CSL_USB_INTRTX_EP0_SHIFT         (0x0000u)
#define CSL_USB_INTRTX_EP0_RESETVAL      (0x0000u)

#define CSL_USB_INTRTX_RESETVAL          (0x0000u)

/* INTRRX */

#define CSL_USB_INTRRX_EP4RX_MASK        (0x0010u)
#define CSL_USB_INTRRX_EP4RX_SHIFT       (0x0004u)
#define CSL_USB_INTRRX_EP4RX_RESETVAL    (0x0000u)

#define CSL_USB_INTRRX_EP3RX_MASK        (0x0008u)
#define CSL_USB_INTRRX_EP3RX_SHIFT       (0x0003u)
#define CSL_USB_INTRRX_EP3RX_RESETVAL    (0x0000u)

#define CSL_USB_INTRRX_EP2RX_MASK        (0x0004u)
#define CSL_USB_INTRRX_EP2RX_SHIFT       (0x0002u)
#define CSL_USB_INTRRX_EP2RX_RESETVAL    (0x0000u)

#define CSL_USB_INTRRX_EP1RX_MASK        (0x0002u)
#define CSL_USB_INTRRX_EP1RX_SHIFT       (0x0001u)
#define CSL_USB_INTRRX_EP1RX_RESETVAL    (0x0000u)

#define CSL_USB_INTRRX_RESETVAL          (0x0000u)

/* INTRTXE */

#define CSL_USB_INTRTXE_EP4TX_MASK       (0x0010u)
#define CSL_USB_INTRTXE_EP4TX_SHIFT      (0x0004u)
#define CSL_USB_INTRTXE_EP4TX_RESETVAL   (0x0001u)

#define CSL_USB_INTRTXE_EP3TX_MASK       (0x0008u)
#define CSL_USB_INTRTXE_EP3TX_SHIFT      (0x0003u)
#define CSL_USB_INTRTXE_EP3TX_RESETVAL   (0x0001u)

#define CSL_USB_INTRTXE_EP2TX_MASK       (0x0004u)
#define CSL_USB_INTRTXE_EP2TX_SHIFT      (0x0002u)
#define CSL_USB_INTRTXE_EP2TX_RESETVAL   (0x0001u)

#define CSL_USB_INTRTXE_EP1TX_MASK       (0x0002u)
#define CSL_USB_INTRTXE_EP1TX_SHIFT      (0x0001u)
#define CSL_USB_INTRTXE_EP1TX_RESETVAL   (0x0001u)

#define CSL_USB_INTRTXE_EP0_MASK         (0x0001u)
#define CSL_USB_INTRTXE_EP0_SHIFT        (0x0000u)
#define CSL_USB_INTRTXE_EP0_RESETVAL     (0x0001u)

#define CSL_USB_INTRTXE_RESETVAL         (0x001Fu)

/* INTRRXE */

#define CSL_USB_INTRRXE_EP4RX_MASK       (0x0010u)
#define CSL_USB_INTRRXE_EP4RX_SHIFT      (0x0004u)
#define CSL_USB_INTRRXE_EP4RX_RESETVAL   (0x0001u)

#define CSL_USB_INTRRXE_EP3RX_MASK       (0x0008u)
#define CSL_USB_INTRRXE_EP3RX_SHIFT      (0x0003u)
#define CSL_USB_INTRRXE_EP3RX_RESETVAL   (0x0001u)

#define CSL_USB_INTRRXE_EP2RX_MASK       (0x0004u)
#define CSL_USB_INTRRXE_EP2RX_SHIFT      (0x0002u)
#define CSL_USB_INTRRXE_EP2RX_RESETVAL   (0x0001u)

#define CSL_USB_INTRRXE_EP1RX_MASK       (0x0002u)
#define CSL_USB_INTRRXE_EP1RX_SHIFT      (0x0001u)
#define CSL_USB_INTRRXE_EP1RX_RESETVAL   (0x0001u)

#define CSL_USB_INTRRXE_RESETVAL         (0x001Eu)

/* INTRUSB */

#define CSL_USB_INTRUSB_VBUSERR_MASK     (0x80u)
#define CSL_USB_INTRUSB_VBUSERR_SHIFT    (0x07u)
#define CSL_USB_INTRUSB_VBUSERR_RESETVAL (0x00u)

#define CSL_USB_INTRUSB_SESSREQ_MASK     (0x40u)
#define CSL_USB_INTRUSB_SESSREQ_SHIFT    (0x06u)
#define CSL_USB_INTRUSB_SESSREQ_RESETVAL (0x00u)

#define CSL_USB_INTRUSB_DISCON_MASK      (0x20u)
#define CSL_USB_INTRUSB_DISCON_SHIFT     (0x05u)
#define CSL_USB_INTRUSB_DISCON_RESETVAL  (0x00u)

#define CSL_USB_INTRUSB_CONN_MASK        (0x10u)
#define CSL_USB_INTRUSB_CONN_SHIFT       (0x04u)
#define CSL_USB_INTRUSB_CONN_RESETVAL    (0x00u)

#define CSL_USB_INTRUSB_SOF_MASK         (0x08u)
#define CSL_USB_INTRUSB_SOF_SHIFT        (0x03u)
#define CSL_USB_INTRUSB_SOF_RESETVAL     (0x00u)

#define CSL_USB_INTRUSB_RESET_BABBLE_MASK (0x04u)
#define CSL_USB_INTRUSB_RESET_BABBLE_SHIFT (0x02u)
#define CSL_USB_INTRUSB_RESET_BABBLE_RESETVAL (0x00u)

#define CSL_USB_INTRUSB_RESUME_MASK      (0x02u)
#define CSL_USB_INTRUSB_RESUME_SHIFT     (0x01u)
#define CSL_USB_INTRUSB_RESUME_RESETVAL  (0x00u)

#define CSL_USB_INTRUSB_SUSPEND_MASK     (0x01u)
#define CSL_USB_INTRUSB_SUSPEND_SHIFT    (0x00u)
#define CSL_USB_INTRUSB_SUSPEND_RESETVAL (0x00u)

#define CSL_USB_INTRUSB_RESETVAL         (0x00u)

/* INTRUSBE */

#define CSL_USB_INTRUSBE_VBUSERR_MASK    (0x80u)
#define CSL_USB_INTRUSBE_VBUSERR_SHIFT   (0x07u)
#define CSL_USB_INTRUSBE_VBUSERR_RESETVAL (0x00u)

#define CSL_USB_INTRUSBE_SESSREQ_MASK    (0x40u)
#define CSL_USB_INTRUSBE_SESSREQ_SHIFT   (0x06u)
#define CSL_USB_INTRUSBE_SESSREQ_RESETVAL (0x00u)

#define CSL_USB_INTRUSBE_DISCON_MASK     (0x20u)
#define CSL_USB_INTRUSBE_DISCON_SHIFT    (0x05u)
#define CSL_USB_INTRUSBE_DISCON_RESETVAL (0x00u)

#define CSL_USB_INTRUSBE_CONN_MASK       (0x10u)
#define CSL_USB_INTRUSBE_CONN_SHIFT      (0x04u)
#define CSL_USB_INTRUSBE_CONN_RESETVAL   (0x00u)

#define CSL_USB_INTRUSBE_SOF_MASK        (0x08u)
#define CSL_USB_INTRUSBE_SOF_SHIFT       (0x03u)
#define CSL_USB_INTRUSBE_SOF_RESETVAL    (0x00u)

#define CSL_USB_INTRUSBE_RESET_BABBLE_MASK (0x04u)
#define CSL_USB_INTRUSBE_RESET_BABBLE_SHIFT (0x02u)
#define CSL_USB_INTRUSBE_RESET_BABBLE_RESETVAL (0x01u)

#define CSL_USB_INTRUSBE_RESUME_MASK     (0x02u)
#define CSL_USB_INTRUSBE_RESUME_SHIFT    (0x01u)
#define CSL_USB_INTRUSBE_RESUME_RESETVAL (0x01u)

#define CSL_USB_INTRUSBE_SUSPEND_MASK    (0x01u)
#define CSL_USB_INTRUSBE_SUSPEND_SHIFT   (0x00u)
#define CSL_USB_INTRUSBE_SUSPEND_RESETVAL (0x00u)

#define CSL_USB_INTRUSBE_RESETVAL        (0x06u)

/* FRAME */

#define CSL_USB_FRAME_FRAMENUMBER_MASK   (0x07FFu)
#define CSL_USB_FRAME_FRAMENUMBER_SHIFT  (0x0000u)
#define CSL_USB_FRAME_FRAMENUMBER_RESETVAL (0x0000u)

#define CSL_USB_FRAME_RESETVAL           (0x0000u)

/* INDEX */

#define CSL_USB_INDEX_EPSEL_MASK         (0x0Fu)
#define CSL_USB_INDEX_EPSEL_SHIFT        (0x00u)
#define CSL_USB_INDEX_EPSEL_RESETVAL     (0x00u)

#define CSL_USB_INDEX_RESETVAL           (0x00u)

/* TESTMODE */

#define CSL_USB_TESTMODE_FORCE_HOST_MASK (0x80u)
#define CSL_USB_TESTMODE_FORCE_HOST_SHIFT (0x07u)
#define CSL_USB_TESTMODE_FORCE_HOST_RESETVAL (0x00u)

#define CSL_USB_TESTMODE_FIFO_ACCESS_MASK (0x40u)
#define CSL_USB_TESTMODE_FIFO_ACCESS_SHIFT (0x06u)
#define CSL_USB_TESTMODE_FIFO_ACCESS_RESETVAL (0x00u)

#define CSL_USB_TESTMODE_FORCE_FS_MASK   (0x20u)
#define CSL_USB_TESTMODE_FORCE_FS_SHIFT  (0x05u)
#define CSL_USB_TESTMODE_FORCE_FS_RESETVAL (0x00u)

#define CSL_USB_TESTMODE_FORCE_HS_MASK   (0x10u)
#define CSL_USB_TESTMODE_FORCE_HS_SHIFT  (0x04u)
#define CSL_USB_TESTMODE_FORCE_HS_RESETVAL (0x00u)

#define CSL_USB_TESTMODE_TEST_PACKET_MASK (0x08u)
#define CSL_USB_TESTMODE_TEST_PACKET_SHIFT (0x03u)
#define CSL_USB_TESTMODE_TEST_PACKET_RESETVAL (0x00u)

#define CSL_USB_TESTMODE_TEST_K_MASK     (0x04u)
#define CSL_USB_TESTMODE_TEST_K_SHIFT    (0x02u)
#define CSL_USB_TESTMODE_TEST_K_RESETVAL (0x00u)

#define CSL_USB_TESTMODE_TEST_J_MASK     (0x02u)
#define CSL_USB_TESTMODE_TEST_J_SHIFT    (0x01u)
#define CSL_USB_TESTMODE_TEST_J_RESETVAL (0x00u)

#define CSL_USB_TESTMODE_TEST_SE0_NAK_MASK (0x01u)
#define CSL_USB_TESTMODE_TEST_SE0_NAK_SHIFT (0x00u)
#define CSL_USB_TESTMODE_TEST_SE0_NAK_RESETVAL (0x00u)

#define CSL_USB_TESTMODE_RESETVAL        (0x00u)

/* TXMAXP */

#define CSL_USB_TXMAXP_MAXPAYLOAD_MASK   (0x07FFu)
#define CSL_USB_TXMAXP_MAXPAYLOAD_SHIFT  (0x0000u)
#define CSL_USB_TXMAXP_MAXPAYLOAD_RESETVAL (0x0000u)

#define CSL_USB_TXMAXP_RESETVAL          (0x0000u)

/* PERI_CSR0 */

#define CSL_USB_PERI_CSR0_FLUSHFIFO_MASK (0x0100u)
#define CSL_USB_PERI_CSR0_FLUSHFIFO_SHIFT (0x0008u)
#define CSL_USB_PERI_CSR0_FLUSHFIFO_RESETVAL (0x0000u)

#define CSL_USB_PERI_CSR0_SERV_SETUPEND_MASK (0x0080u)
#define CSL_USB_PERI_CSR0_SERV_SETUPEND_SHIFT (0x0007u)
#define CSL_USB_PERI_CSR0_SERV_SETUPEND_RESETVAL (0x0000u)

#define CSL_USB_PERI_CSR0_SERV_RXPKTRDY_MASK (0x0040u)
#define CSL_USB_PERI_CSR0_SERV_RXPKTRDY_SHIFT (0x0006u)
#define CSL_USB_PERI_CSR0_SERV_RXPKTRDY_RESETVAL (0x0000u)

#define CSL_USB_PERI_CSR0_SENDSTALL_MASK (0x0020u)
#define CSL_USB_PERI_CSR0_SENDSTALL_SHIFT (0x0005u)
#define CSL_USB_PERI_CSR0_SENDSTALL_RESETVAL (0x0000u)

#define CSL_USB_PERI_CSR0_SETUPEND_MASK  (0x0010u)
#define CSL_USB_PERI_CSR0_SETUPEND_SHIFT (0x0004u)
#define CSL_USB_PERI_CSR0_SETUPEND_RESETVAL (0x0000u)

#define CSL_USB_PERI_CSR0_DATAEND_MASK   (0x0008u)
#define CSL_USB_PERI_CSR0_DATAEND_SHIFT  (0x0003u)
#define CSL_USB_PERI_CSR0_DATAEND_RESETVAL (0x0000u)

#define CSL_USB_PERI_CSR0_SENTSTALL_MASK (0x0004u)
#define CSL_USB_PERI_CSR0_SENTSTALL_SHIFT (0x0002u)
#define CSL_USB_PERI_CSR0_SENTSTALL_RESETVAL (0x0000u)

#define CSL_USB_PERI_CSR0_TXPKTRDY_MASK  (0x0002u)
#define CSL_USB_PERI_CSR0_TXPKTRDY_SHIFT (0x0001u)
#define CSL_USB_PERI_CSR0_TXPKTRDY_RESETVAL (0x0000u)

#define CSL_USB_PERI_CSR0_RXPKTRDY_MASK  (0x0001u)
#define CSL_USB_PERI_CSR0_RXPKTRDY_SHIFT (0x0000u)
#define CSL_USB_PERI_CSR0_RXPKTRDY_RESETVAL (0x0000u)

#define CSL_USB_PERI_CSR0_RESETVAL       (0x0000u)

/* HOST_CSR0 */

#define CSL_USB_HOST_CSR0_DATATOGWREN_MASK (0x0400u)
#define CSL_USB_HOST_CSR0_DATATOGWREN_SHIFT (0x000Au)
#define CSL_USB_HOST_CSR0_DATATOGWREN_RESETVAL (0x0000u)

#define CSL_USB_HOST_CSR0_DATATOG_MASK   (0x0200u)
#define CSL_USB_HOST_CSR0_DATATOG_SHIFT  (0x0009u)
#define CSL_USB_HOST_CSR0_DATATOG_RESETVAL (0x0000u)

#define CSL_USB_HOST_CSR0_FLUSHFIFO_MASK (0x0100u)
#define CSL_USB_HOST_CSR0_FLUSHFIFO_SHIFT (0x0008u)
#define CSL_USB_HOST_CSR0_FLUSHFIFO_RESETVAL (0x0000u)

#define CSL_USB_HOST_CSR0_NAK_TIMEOUT_MASK (0x0080u)
#define CSL_USB_HOST_CSR0_NAK_TIMEOUT_SHIFT (0x0007u)
#define CSL_USB_HOST_CSR0_NAK_TIMEOUT_RESETVAL (0x0000u)

#define CSL_USB_HOST_CSR0_STATUSPKT_MASK (0x0040u)
#define CSL_USB_HOST_CSR0_STATUSPKT_SHIFT (0x0006u)
#define CSL_USB_HOST_CSR0_STATUSPKT_RESETVAL (0x0000u)

#define CSL_USB_HOST_CSR0_REQPKT_MASK    (0x0020u)
#define CSL_USB_HOST_CSR0_REQPKT_SHIFT   (0x0005u)
#define CSL_USB_HOST_CSR0_REQPKT_RESETVAL (0x0000u)

#define CSL_USB_HOST_CSR0_ERROR_MASK     (0x0010u)
#define CSL_USB_HOST_CSR0_ERROR_SHIFT    (0x0004u)
#define CSL_USB_HOST_CSR0_ERROR_RESETVAL (0x0000u)

#define CSL_USB_HOST_CSR0_SETUPPKT_MASK  (0x0008u)
#define CSL_USB_HOST_CSR0_SETUPPKT_SHIFT (0x0003u)
#define CSL_USB_HOST_CSR0_SETUPPKT_RESETVAL (0x0000u)

#define CSL_USB_HOST_CSR0_RXSTALL_MASK   (0x0004u)
#define CSL_USB_HOST_CSR0_RXSTALL_SHIFT  (0x0002u)
#define CSL_USB_HOST_CSR0_RXSTALL_RESETVAL (0x0000u)

#define CSL_USB_HOST_CSR0_TXPKTRDY_MASK  (0x0002u)
#define CSL_USB_HOST_CSR0_TXPKTRDY_SHIFT (0x0001u)
#define CSL_USB_HOST_CSR0_TXPKTRDY_RESETVAL (0x0000u)

#define CSL_USB_HOST_CSR0_RXPKTRDY_MASK  (0x0001u)
#define CSL_USB_HOST_CSR0_RXPKTRDY_SHIFT (0x0000u)
#define CSL_USB_HOST_CSR0_RXPKTRDY_RESETVAL (0x0000u)

#define CSL_USB_HOST_CSR0_RESETVAL       (0x0000u)

/* PERI_TXCSR */

#define CSL_USB_PERI_TXCSR_AUTOSET_MASK  (0x8000u)
#define CSL_USB_PERI_TXCSR_AUTOSET_SHIFT (0x000Fu)
#define CSL_USB_PERI_TXCSR_AUTOSET_RESETVAL (0x0000u)

#define CSL_USB_PERI_TXCSR_ISO_MASK      (0x4000u)
#define CSL_USB_PERI_TXCSR_ISO_SHIFT     (0x000Eu)
#define CSL_USB_PERI_TXCSR_ISO_RESETVAL  (0x0000u)

#define CSL_USB_PERI_TXCSR_MODE_MASK     (0x2000u)
#define CSL_USB_PERI_TXCSR_MODE_SHIFT    (0x000Du)
#define CSL_USB_PERI_TXCSR_MODE_RESETVAL (0x0000u)

#define CSL_USB_PERI_TXCSR_DMAEN_MASK    (0x1000u)
#define CSL_USB_PERI_TXCSR_DMAEN_SHIFT   (0x000Cu)
#define CSL_USB_PERI_TXCSR_DMAEN_RESETVAL (0x0000u)

#define CSL_USB_PERI_TXCSR_FRCDATATOG_MASK (0x0800u)
#define CSL_USB_PERI_TXCSR_FRCDATATOG_SHIFT (0x000Bu)
#define CSL_USB_PERI_TXCSR_FRCDATATOG_RESETVAL (0x0000u)

#define CSL_USB_PERI_TXCSR_DMAMODE_MASK  (0x0400u)
#define CSL_USB_PERI_TXCSR_DMAMODE_SHIFT (0x000Au)
#define CSL_USB_PERI_TXCSR_DMAMODE_RESETVAL (0x0000u)

#define CSL_USB_PERI_TXCSR_CLRDATATOG_MASK (0x0040u)
#define CSL_USB_PERI_TXCSR_CLRDATATOG_SHIFT (0x0006u)
#define CSL_USB_PERI_TXCSR_CLRDATATOG_RESETVAL (0x0000u)

#define CSL_USB_PERI_TXCSR_SENTSTALL_MASK (0x0020u)
#define CSL_USB_PERI_TXCSR_SENTSTALL_SHIFT (0x0005u)
#define CSL_USB_PERI_TXCSR_SENTSTALL_RESETVAL (0x0000u)

#define CSL_USB_PERI_TXCSR_SENDSTALL_MASK (0x0010u)
#define CSL_USB_PERI_TXCSR_SENDSTALL_SHIFT (0x0004u)
#define CSL_USB_PERI_TXCSR_SENDSTALL_RESETVAL (0x0000u)

#define CSL_USB_PERI_TXCSR_FLUSHFIFO_MASK (0x0008u)
#define CSL_USB_PERI_TXCSR_FLUSHFIFO_SHIFT (0x0003u)
#define CSL_USB_PERI_TXCSR_FLUSHFIFO_RESETVAL (0x0000u)

#define CSL_USB_PERI_TXCSR_UNDERRUN_MASK (0x0004u)
#define CSL_USB_PERI_TXCSR_UNDERRUN_SHIFT (0x0002u)
#define CSL_USB_PERI_TXCSR_UNDERRUN_RESETVAL (0x0000u)

#define CSL_USB_PERI_TXCSR_FIFONOTEMPTY_MASK (0x0002u)
#define CSL_USB_PERI_TXCSR_FIFONOTEMPTY_SHIFT (0x0001u)
#define CSL_USB_PERI_TXCSR_FIFONOTEMPTY_RESETVAL (0x0000u)

#define CSL_USB_PERI_TXCSR_TXPKTRDY_MASK (0x0001u)
#define CSL_USB_PERI_TXCSR_TXPKTRDY_SHIFT (0x0000u)
#define CSL_USB_PERI_TXCSR_TXPKTRDY_RESETVAL (0x0000u)

#define CSL_USB_PERI_TXCSR_RESETVAL      (0x0000u)

/* HOST_TXCSR */

#define CSL_USB_HOST_TXCSR_AUTOSET_MASK  (0x8000u)
#define CSL_USB_HOST_TXCSR_AUTOSET_SHIFT (0x000Fu)
#define CSL_USB_HOST_TXCSR_AUTOSET_RESETVAL (0x0000u)

#define CSL_USB_HOST_TXCSR_MODE_MASK     (0x2000u)
#define CSL_USB_HOST_TXCSR_MODE_SHIFT    (0x000Du)
#define CSL_USB_HOST_TXCSR_MODE_RESETVAL (0x0000u)

#define CSL_USB_HOST_TXCSR_DMAEN_MASK    (0x1000u)
#define CSL_USB_HOST_TXCSR_DMAEN_SHIFT   (0x000Cu)
#define CSL_USB_HOST_TXCSR_DMAEN_RESETVAL (0x0000u)

#define CSL_USB_HOST_TXCSR_FRCDATATOG_MASK (0x0800u)
#define CSL_USB_HOST_TXCSR_FRCDATATOG_SHIFT (0x000Bu)
#define CSL_USB_HOST_TXCSR_FRCDATATOG_RESETVAL (0x0000u)

#define CSL_USB_HOST_TXCSR_DMAMODE_MASK  (0x0400u)
#define CSL_USB_HOST_TXCSR_DMAMODE_SHIFT (0x000Au)
#define CSL_USB_HOST_TXCSR_DMAMODE_RESETVAL (0x0000u)

#define CSL_USB_HOST_TXCSR_DATATOGWREN_MASK (0x0200u)
#define CSL_USB_HOST_TXCSR_DATATOGWREN_SHIFT (0x0009u)
#define CSL_USB_HOST_TXCSR_DATATOGWREN_RESETVAL (0x0000u)

#define CSL_USB_HOST_TXCSR_DATATOG_MASK  (0x0100u)
#define CSL_USB_HOST_TXCSR_DATATOG_SHIFT (0x0008u)
#define CSL_USB_HOST_TXCSR_DATATOG_RESETVAL (0x0000u)

#define CSL_USB_HOST_TXCSR_NAK_TIMEOUT_MASK (0x0080u)
#define CSL_USB_HOST_TXCSR_NAK_TIMEOUT_SHIFT (0x0007u)
#define CSL_USB_HOST_TXCSR_NAK_TIMEOUT_RESETVAL (0x0000u)

#define CSL_USB_HOST_TXCSR_CLRDATATOG_MASK (0x0040u)
#define CSL_USB_HOST_TXCSR_CLRDATATOG_SHIFT (0x0006u)
#define CSL_USB_HOST_TXCSR_CLRDATATOG_RESETVAL (0x0000u)

#define CSL_USB_HOST_TXCSR_RXSTALL_MASK  (0x0020u)
#define CSL_USB_HOST_TXCSR_RXSTALL_SHIFT (0x0005u)
#define CSL_USB_HOST_TXCSR_RXSTALL_RESETVAL (0x0000u)

#define CSL_USB_HOST_TXCSR_SETUPPKT_MASK (0x0010u)
#define CSL_USB_HOST_TXCSR_SETUPPKT_SHIFT (0x0004u)
#define CSL_USB_HOST_TXCSR_SETUPPKT_RESETVAL (0x0000u)

#define CSL_USB_HOST_TXCSR_FLUSHFIFO_MASK (0x0008u)
#define CSL_USB_HOST_TXCSR_FLUSHFIFO_SHIFT (0x0003u)
#define CSL_USB_HOST_TXCSR_FLUSHFIFO_RESETVAL (0x0000u)

#define CSL_USB_HOST_TXCSR_ERROR_MASK    (0x0004u)
#define CSL_USB_HOST_TXCSR_ERROR_SHIFT   (0x0002u)
#define CSL_USB_HOST_TXCSR_ERROR_RESETVAL (0x0000u)

#define CSL_USB_HOST_TXCSR_FIFONOTEMPTY_MASK (0x0002u)
#define CSL_USB_HOST_TXCSR_FIFONOTEMPTY_SHIFT (0x0001u)
#define CSL_USB_HOST_TXCSR_FIFONOTEMPTY_RESETVAL (0x0000u)

#define CSL_USB_HOST_TXCSR_TXPKTRDY_MASK (0x0001u)
#define CSL_USB_HOST_TXCSR_TXPKTRDY_SHIFT (0x0000u)
#define CSL_USB_HOST_TXCSR_TXPKTRDY_RESETVAL (0x0000u)

#define CSL_USB_HOST_TXCSR_RESETVAL      (0x0000u)

/* RXMAXP */

#define CSL_USB_RXMAXP_MAXPAYLOAD_MASK   (0x07FFu)
#define CSL_USB_RXMAXP_MAXPAYLOAD_SHIFT  (0x0000u)
#define CSL_USB_RXMAXP_MAXPAYLOAD_RESETVAL (0x0000u)

#define CSL_USB_RXMAXP_RESETVAL          (0x0000u)

/* PERI_RXCSR */

#define CSL_USB_PERI_RXCSR_AUTOCLEAR_MASK (0x8000u)
#define CSL_USB_PERI_RXCSR_AUTOCLEAR_SHIFT (0x000Fu)
#define CSL_USB_PERI_RXCSR_AUTOCLEAR_RESETVAL (0x0000u)

#define CSL_USB_PERI_RXCSR_ISO_MASK      (0x4000u)
#define CSL_USB_PERI_RXCSR_ISO_SHIFT     (0x000Eu)
#define CSL_USB_PERI_RXCSR_ISO_RESETVAL  (0x0000u)

#define CSL_USB_PERI_RXCSR_DMAEN_MASK    (0x2000u)
#define CSL_USB_PERI_RXCSR_DMAEN_SHIFT   (0x000Du)
#define CSL_USB_PERI_RXCSR_DMAEN_RESETVAL (0x0000u)

#define CSL_USB_PERI_RXCSR_DISNYET_MASK  (0x1000u)
#define CSL_USB_PERI_RXCSR_DISNYET_SHIFT (0x000Cu)
#define CSL_USB_PERI_RXCSR_DISNYET_RESETVAL (0x0000u)

#define CSL_USB_PERI_RXCSR_DMAMODE_MASK  (0x0800u)
#define CSL_USB_PERI_RXCSR_DMAMODE_SHIFT (0x000Bu)
#define CSL_USB_PERI_RXCSR_DMAMODE_RESETVAL (0x0000u)

#define CSL_USB_PERI_RXCSR_CLRDATATOG_MASK (0x0080u)
#define CSL_USB_PERI_RXCSR_CLRDATATOG_SHIFT (0x0007u)
#define CSL_USB_PERI_RXCSR_CLRDATATOG_RESETVAL (0x0000u)

#define CSL_USB_PERI_RXCSR_SENTSTALL_MASK (0x0040u)
#define CSL_USB_PERI_RXCSR_SENTSTALL_SHIFT (0x0006u)
#define CSL_USB_PERI_RXCSR_SENTSTALL_RESETVAL (0x0000u)

#define CSL_USB_PERI_RXCSR_SENDSTALL_MASK (0x0020u)
#define CSL_USB_PERI_RXCSR_SENDSTALL_SHIFT (0x0005u)
#define CSL_USB_PERI_RXCSR_SENDSTALL_RESETVAL (0x0000u)

#define CSL_USB_PERI_RXCSR_FLUSHFIFO_MASK (0x0010u)
#define CSL_USB_PERI_RXCSR_FLUSHFIFO_SHIFT (0x0004u)
#define CSL_USB_PERI_RXCSR_FLUSHFIFO_RESETVAL (0x0000u)

#define CSL_USB_PERI_RXCSR_DATAERROR_MASK (0x0008u)
#define CSL_USB_PERI_RXCSR_DATAERROR_SHIFT (0x0003u)
#define CSL_USB_PERI_RXCSR_DATAERROR_RESETVAL (0x0000u)

#define CSL_USB_PERI_RXCSR_OVERRUN_MASK  (0x0004u)
#define CSL_USB_PERI_RXCSR_OVERRUN_SHIFT (0x0002u)
#define CSL_USB_PERI_RXCSR_OVERRUN_RESETVAL (0x0000u)

#define CSL_USB_PERI_RXCSR_FIFOFULL_MASK (0x0002u)
#define CSL_USB_PERI_RXCSR_FIFOFULL_SHIFT (0x0001u)
#define CSL_USB_PERI_RXCSR_FIFOFULL_RESETVAL (0x0000u)

#define CSL_USB_PERI_RXCSR_RXPKTRDY_MASK (0x0001u)
#define CSL_USB_PERI_RXCSR_RXPKTRDY_SHIFT (0x0000u)
#define CSL_USB_PERI_RXCSR_RXPKTRDY_RESETVAL (0x0000u)

#define CSL_USB_PERI_RXCSR_RESETVAL      (0x0000u)

/* HOST_RXCSR */

#define CSL_USB_HOST_RXCSR_AUTOCLEAR_MASK (0x8000u)
#define CSL_USB_HOST_RXCSR_AUTOCLEAR_SHIFT (0x000Fu)
#define CSL_USB_HOST_RXCSR_AUTOCLEAR_RESETVAL (0x0000u)

#define CSL_USB_HOST_RXCSR_AUTOREQ_MASK  (0x4000u)
#define CSL_USB_HOST_RXCSR_AUTOREQ_SHIFT (0x000Eu)
#define CSL_USB_HOST_RXCSR_AUTOREQ_RESETVAL (0x0000u)

#define CSL_USB_HOST_RXCSR_DMAEN_MASK    (0x2000u)
#define CSL_USB_HOST_RXCSR_DMAEN_SHIFT   (0x000Du)
#define CSL_USB_HOST_RXCSR_DMAEN_RESETVAL (0x0000u)

#define CSL_USB_HOST_RXCSR_DISNYET_MASK  (0x1000u)
#define CSL_USB_HOST_RXCSR_DISNYET_SHIFT (0x000Cu)
#define CSL_USB_HOST_RXCSR_DISNYET_RESETVAL (0x0000u)

#define CSL_USB_HOST_RXCSR_DMAMODE_MASK  (0x0800u)
#define CSL_USB_HOST_RXCSR_DMAMODE_SHIFT (0x000Bu)
#define CSL_USB_HOST_RXCSR_DMAMODE_RESETVAL (0x0000u)

#define CSL_USB_HOST_RXCSR_DATATOGWREN_MASK (0x0400u)
#define CSL_USB_HOST_RXCSR_DATATOGWREN_SHIFT (0x000Au)
#define CSL_USB_HOST_RXCSR_DATATOGWREN_RESETVAL (0x0000u)

#define CSL_USB_HOST_RXCSR_DATATOG_MASK  (0x0200u)
#define CSL_USB_HOST_RXCSR_DATATOG_SHIFT (0x0009u)
#define CSL_USB_HOST_RXCSR_DATATOG_RESETVAL (0x0000u)

#define CSL_USB_HOST_RXCSR_CLRDATATOG_MASK (0x0080u)
#define CSL_USB_HOST_RXCSR_CLRDATATOG_SHIFT (0x0007u)
#define CSL_USB_HOST_RXCSR_CLRDATATOG_RESETVAL (0x0000u)

#define CSL_USB_HOST_RXCSR_RXSTALL_MASK  (0x0040u)
#define CSL_USB_HOST_RXCSR_RXSTALL_SHIFT (0x0006u)
#define CSL_USB_HOST_RXCSR_RXSTALL_RESETVAL (0x0000u)

#define CSL_USB_HOST_RXCSR_REQPKT_MASK   (0x0020u)
#define CSL_USB_HOST_RXCSR_REQPKT_SHIFT  (0x0005u)
#define CSL_USB_HOST_RXCSR_REQPKT_RESETVAL (0x0000u)

#define CSL_USB_HOST_RXCSR_FLUSHFIFO_MASK (0x0010u)
#define CSL_USB_HOST_RXCSR_FLUSHFIFO_SHIFT (0x0004u)
#define CSL_USB_HOST_RXCSR_FLUSHFIFO_RESETVAL (0x0000u)

#define CSL_USB_HOST_RXCSR_DATAERR_NAKTIMEOUT_MASK (0x0008u)
#define CSL_USB_HOST_RXCSR_DATAERR_NAKTIMEOUT_SHIFT (0x0003u)
#define CSL_USB_HOST_RXCSR_DATAERR_NAKTIMEOUT_RESETVAL (0x0000u)

#define CSL_USB_HOST_RXCSR_ERROR_MASK    (0x0004u)
#define CSL_USB_HOST_RXCSR_ERROR_SHIFT   (0x0002u)
#define CSL_USB_HOST_RXCSR_ERROR_RESETVAL (0x0000u)

#define CSL_USB_HOST_RXCSR_FIFOFULL_MASK (0x0002u)
#define CSL_USB_HOST_RXCSR_FIFOFULL_SHIFT (0x0001u)
#define CSL_USB_HOST_RXCSR_FIFOFULL_RESETVAL (0x0000u)

#define CSL_USB_HOST_RXCSR_RXPKTRDY_MASK (0x0001u)
#define CSL_USB_HOST_RXCSR_RXPKTRDY_SHIFT (0x0000u)
#define CSL_USB_HOST_RXCSR_RXPKTRDY_RESETVAL (0x0000u)

#define CSL_USB_HOST_RXCSR_RESETVAL      (0x0000u)

/* COUNT0 */

#define CSL_USB_COUNT0_EP0RXCOUNT_MASK   (0x007Fu)
#define CSL_USB_COUNT0_EP0RXCOUNT_SHIFT  (0x0000u)
#define CSL_USB_COUNT0_EP0RXCOUNT_RESETVAL (0x0000u)

#define CSL_USB_COUNT0_RESETVAL          (0x0000u)

/* RXCOUNT */

#define CSL_USB_RXCOUNT_EPRXCOUNT_MASK   (0x1FFFu)
#define CSL_USB_RXCOUNT_EPRXCOUNT_SHIFT  (0x0000u)
#define CSL_USB_RXCOUNT_EPRXCOUNT_RESETVAL (0x0000u)

#define CSL_USB_RXCOUNT_RESETVAL         (0x0000u)

/* HOST_TYPE0 */

#define CSL_USB_HOST_TYPE0_SPEED_MASK    (0xC0u)
#define CSL_USB_HOST_TYPE0_SPEED_SHIFT   (0x06u)
#define CSL_USB_HOST_TYPE0_SPEED_RESETVAL (0x00u)

#define CSL_USB_HOST_TYPE0_RESETVAL      (0x00u)

/* HOST_TXTYPE */

#define CSL_USB_HOST_TXTYPE_SPEED_MASK   (0xC0u)
#define CSL_USB_HOST_TXTYPE_SPEED_SHIFT  (0x06u)
#define CSL_USB_HOST_TXTYPE_SPEED_RESETVAL (0x00u)

#define CSL_USB_HOST_TXTYPE_PROT_MASK    (0x30u)
#define CSL_USB_HOST_TXTYPE_PROT_SHIFT   (0x04u)
#define CSL_USB_HOST_TXTYPE_PROT_RESETVAL (0x00u)

#define CSL_USB_HOST_TXTYPE_TENDPN_MASK  (0x0Fu)
#define CSL_USB_HOST_TXTYPE_TENDPN_SHIFT (0x00u)
#define CSL_USB_HOST_TXTYPE_TENDPN_RESETVAL (0x00u)

#define CSL_USB_HOST_TXTYPE_RESETVAL     (0x00u)

/* HOST_NAKLIMIT0 */

#define CSL_USB_HOST_NAKLIMIT0_EP0NAKLIMIT_MASK (0x1Fu)
#define CSL_USB_HOST_NAKLIMIT0_EP0NAKLIMIT_SHIFT (0x00u)
#define CSL_USB_HOST_NAKLIMIT0_EP0NAKLIMIT_RESETVAL (0x00u)

#define CSL_USB_HOST_NAKLIMIT0_RESETVAL  (0x00u)

/* HOST_TXINTERVAL */

#define CSL_USB_HOST_TXINTERVAL_POLINTVL_NAKLIMIT_MASK (0xFFu)
#define CSL_USB_HOST_TXINTERVAL_POLINTVL_NAKLIMIT_SHIFT (0x00u)
#define CSL_USB_HOST_TXINTERVAL_POLINTVL_NAKLIMIT_RESETVAL (0x00u)

#define CSL_USB_HOST_TXINTERVAL_RESETVAL (0x00u)

/* HOST_RXTYPE */

#define CSL_USB_HOST_RXTYPE_SPEED_MASK   (0xC0u)
#define CSL_USB_HOST_RXTYPE_SPEED_SHIFT  (0x06u)
#define CSL_USB_HOST_RXTYPE_SPEED_RESETVAL (0x00u)

#define CSL_USB_HOST_RXTYPE_PROT_MASK    (0x30u)
#define CSL_USB_HOST_RXTYPE_PROT_SHIFT   (0x04u)
#define CSL_USB_HOST_RXTYPE_PROT_RESETVAL (0x00u)

#define CSL_USB_HOST_RXTYPE_RENDPN_MASK  (0x0Fu)
#define CSL_USB_HOST_RXTYPE_RENDPN_SHIFT (0x00u)
#define CSL_USB_HOST_RXTYPE_RENDPN_RESETVAL (0x00u)

#define CSL_USB_HOST_RXTYPE_RESETVAL     (0x00u)

/* HOST_RXINTERVAL */

#define CSL_USB_HOST_RXINTERVAL_POLINTVL_NAKLIMIT_MASK (0xFFu)
#define CSL_USB_HOST_RXINTERVAL_POLINTVL_NAKLIMIT_SHIFT (0x00u)
#define CSL_USB_HOST_RXINTERVAL_POLINTVL_NAKLIMIT_RESETVAL (0x00u)

#define CSL_USB_HOST_RXINTERVAL_RESETVAL (0x00u)

/* CONFIGDATA */

#define CSL_USB_CONFIGDATA_MPRXE_MASK    (0x80u)
#define CSL_USB_CONFIGDATA_MPRXE_SHIFT   (0x07u)
#define CSL_USB_CONFIGDATA_MPRXE_RESETVAL (0x00u)

#define CSL_USB_CONFIGDATA_MPTXE_MASK    (0x40u)
#define CSL_USB_CONFIGDATA_MPTXE_SHIFT   (0x06u)
#define CSL_USB_CONFIGDATA_MPTXE_RESETVAL (0x00u)

#define CSL_USB_CONFIGDATA_BIGENDIAN_MASK (0x20u)
#define CSL_USB_CONFIGDATA_BIGENDIAN_SHIFT (0x05u)
#define CSL_USB_CONFIGDATA_BIGENDIAN_RESETVAL (0x00u)

#define CSL_USB_CONFIGDATA_HBRXE_MASK    (0x10u)
#define CSL_USB_CONFIGDATA_HBRXE_SHIFT   (0x04u)
#define CSL_USB_CONFIGDATA_HBRXE_RESETVAL (0x00u)

#define CSL_USB_CONFIGDATA_HBTXE_MASK    (0x08u)
#define CSL_USB_CONFIGDATA_HBTXE_SHIFT   (0x03u)
#define CSL_USB_CONFIGDATA_HBTXE_RESETVAL (0x00u)

#define CSL_USB_CONFIGDATA_DYNFIFO_MASK  (0x04u)
#define CSL_USB_CONFIGDATA_DYNFIFO_SHIFT (0x02u)
#define CSL_USB_CONFIGDATA_DYNFIFO_RESETVAL (0x00u)

#define CSL_USB_CONFIGDATA_SOFTCONE_MASK (0x02u)
#define CSL_USB_CONFIGDATA_SOFTCONE_SHIFT (0x01u)
#define CSL_USB_CONFIGDATA_SOFTCONE_RESETVAL (0x00u)

#define CSL_USB_CONFIGDATA_UTMIDATAWIDTH_MASK (0x01u)
#define CSL_USB_CONFIGDATA_UTMIDATAWIDTH_SHIFT (0x00u)
#define CSL_USB_CONFIGDATA_UTMIDATAWIDTH_RESETVAL (0x00u)

#define CSL_USB_CONFIGDATA_RESETVAL      (0x00u)

/* FIFOSIZE */

#define CSL_USB_FIFOSIZE_RXFIFOSZ_MASK   (0xF0u)
#define CSL_USB_FIFOSIZE_RXFIFOSZ_SHIFT  (0x04u)
#define CSL_USB_FIFOSIZE_RXFIFOSZ_RESETVAL (0x00u)

#define CSL_USB_FIFOSIZE_TXFIFOSZ_MASK   (0x0Fu)
#define CSL_USB_FIFOSIZE_TXFIFOSZ_SHIFT  (0x00u)
#define CSL_USB_FIFOSIZE_TXFIFOSZ_RESETVAL (0x00u)

#define CSL_USB_FIFOSIZE_RESETVAL        (0x00u)

/* FIFO0 */

#define CSL_USB_FIFO0_DATA_MASK          (0xFFFFFFFFu)
#define CSL_USB_FIFO0_DATA_SHIFT         (0x00000000u)
#define CSL_USB_FIFO0_DATA_RESETVAL      (0x00000000u)

#define CSL_USB_FIFO0_RESETVAL           (0x00000000u)

/* FIFO1 */

#define CSL_USB_FIFO1_DATA_MASK          (0xFFFFFFFFu)
#define CSL_USB_FIFO1_DATA_SHIFT         (0x00000000u)
#define CSL_USB_FIFO1_DATA_RESETVAL      (0x00000000u)

#define CSL_USB_FIFO1_RESETVAL           (0x00000000u)

/* FIFO2 */

#define CSL_USB_FIFO2_DATA_MASK          (0xFFFFFFFFu)
#define CSL_USB_FIFO2_DATA_SHIFT         (0x00000000u)
#define CSL_USB_FIFO2_DATA_RESETVAL      (0x00000000u)

#define CSL_USB_FIFO2_RESETVAL           (0x00000000u)

/* FIFO3 */

#define CSL_USB_FIFO3_DATA_MASK          (0xFFFFFFFFu)
#define CSL_USB_FIFO3_DATA_SHIFT         (0x00000000u)
#define CSL_USB_FIFO3_DATA_RESETVAL      (0x00000000u)

#define CSL_USB_FIFO3_RESETVAL           (0x00000000u)

/* FIFO4 */

#define CSL_USB_FIFO4_DATA_MASK          (0xFFFFFFFFu)
#define CSL_USB_FIFO4_DATA_SHIFT         (0x00000000u)
#define CSL_USB_FIFO4_DATA_RESETVAL      (0x00000000u)

#define CSL_USB_FIFO4_RESETVAL           (0x00000000u)

/* DEVCTL */

#define CSL_USB_DEVCTL_BDEVICE_MASK      (0x80u)
#define CSL_USB_DEVCTL_BDEVICE_SHIFT     (0x07u)
#define CSL_USB_DEVCTL_BDEVICE_RESETVAL  (0x00u)

#define CSL_USB_DEVCTL_FSDEV_MASK        (0x40u)
#define CSL_USB_DEVCTL_FSDEV_SHIFT       (0x06u)
#define CSL_USB_DEVCTL_FSDEV_RESETVAL    (0x00u)

#define CSL_USB_DEVCTL_LSDEV_MASK        (0x20u)
#define CSL_USB_DEVCTL_LSDEV_SHIFT       (0x05u)
#define CSL_USB_DEVCTL_LSDEV_RESETVAL    (0x00u)

#define CSL_USB_DEVCTL_VBUS_MASK         (0x18u)
#define CSL_USB_DEVCTL_VBUS_SHIFT        (0x03u)
#define CSL_USB_DEVCTL_VBUS_RESETVAL     (0x00u)

#define CSL_USB_DEVCTL_HOSTMODE_MASK     (0x04u)
#define CSL_USB_DEVCTL_HOSTMODE_SHIFT    (0x02u)
#define CSL_USB_DEVCTL_HOSTMODE_RESETVAL (0x00u)

#define CSL_USB_DEVCTL_HOSTREQ_MASK      (0x02u)
#define CSL_USB_DEVCTL_HOSTREQ_SHIFT     (0x01u)
#define CSL_USB_DEVCTL_HOSTREQ_RESETVAL  (0x00u)

#define CSL_USB_DEVCTL_SESSION_MASK      (0x01u)
#define CSL_USB_DEVCTL_SESSION_SHIFT     (0x00u)
#define CSL_USB_DEVCTL_SESSION_RESETVAL  (0x00u)

#define CSL_USB_DEVCTL_RESETVAL          (0x00u)

/* TXFIFOSZ */

#define CSL_USB_TXFIFOSZ_DPB_MASK        (0x10u)
#define CSL_USB_TXFIFOSZ_DPB_SHIFT       (0x04u)
#define CSL_USB_TXFIFOSZ_DPB_RESETVAL    (0x00u)

#define CSL_USB_TXFIFOSZ_SZ_MASK         (0x0Fu)
#define CSL_USB_TXFIFOSZ_SZ_SHIFT        (0x00u)
#define CSL_USB_TXFIFOSZ_SZ_RESETVAL     (0x00u)

#define CSL_USB_TXFIFOSZ_RESETVAL        (0x00u)

/* RXFIFOSZ */

#define CSL_USB_RXFIFOSZ_DPB_MASK        (0x10u)
#define CSL_USB_RXFIFOSZ_DPB_SHIFT       (0x04u)
#define CSL_USB_RXFIFOSZ_DPB_RESETVAL    (0x00u)

#define CSL_USB_RXFIFOSZ_SZ_MASK         (0x0Fu)
#define CSL_USB_RXFIFOSZ_SZ_SHIFT        (0x00u)
#define CSL_USB_RXFIFOSZ_SZ_RESETVAL     (0x00u)

#define CSL_USB_RXFIFOSZ_RESETVAL        (0x00u)

/* TXFIFOADDR */

#define CSL_USB_TXFIFOADDR_ADDR_MASK     (0x1FFFu)
#define CSL_USB_TXFIFOADDR_ADDR_SHIFT    (0x0000u)
#define CSL_USB_TXFIFOADDR_ADDR_RESETVAL (0x0000u)

#define CSL_USB_TXFIFOADDR_RESETVAL      (0x0000u)

/* RXFIFOADDR */

#define CSL_USB_RXFIFOADDR_ADDR_MASK     (0x1FFFu)
#define CSL_USB_RXFIFOADDR_ADDR_SHIFT    (0x0000u)
#define CSL_USB_RXFIFOADDR_ADDR_RESETVAL (0x0000u)

#define CSL_USB_RXFIFOADDR_RESETVAL      (0x0000u)

/* HWVERS */

#define CSL_USB20_HWVERS_RTLREL_MASK     (0x8000u)
#define CSL_USB20_HWVERS_RTLREL_SHIFT    (0x000Fu)
#define CSL_USB20_HWVERS_RTLREL_RESETVAL (0x0000u)
#define CSL_USB20_HWVERS_RTLREL_FULL_RELEASE (0x0000u)
#define CSL_USB20_HWVERS_RTLREL_RELEASE_RELEASE (0x0001u)

#define CSL_USB20_HWVERS_MAJORVER_MASK   (0x7C00u)
#define CSL_USB20_HWVERS_MAJORVER_SHIFT  (0x000Au)
#define CSL_USB20_HWVERS_MAJORVER_RESETVAL (0x0000u)

#define CSL_USB20_HWVERS_MINORVER_MASK   (0x03FFu)
#define CSL_USB20_HWVERS_MINORVER_SHIFT  (0x0000u)
#define CSL_USB20_HWVERS_MINORVER_RESETVAL (0x0000u)

#define CSL_USB20_HWVERS_RESETVAL        (0x0000u)

/* EPINFO */

#define CSL_USB20_EPINFO_RXEPNUMSUP_MASK (0xF0u)
#define CSL_USB20_EPINFO_RXEPNUMSUP_SHIFT (0x04u)
#define CSL_USB20_EPINFO_RXEPNUMSUP_RESETVAL (0x00u)

#define CSL_USB20_EPINFO_TXEPNUMSUP_MASK (0x0Fu)
#define CSL_USB20_EPINFO_TXEPNUMSUP_SHIFT (0x00u)
#define CSL_USB20_EPINFO_TXEPNUMSUP_RESETVAL (0x00u)

#define CSL_USB20_EPINFO_RESETVAL        (0x00u)

/* RAMINFO */

#define CSL_USB20_RAMINFO_DMACHSUP_MASK  (0xF0u)
#define CSL_USB20_RAMINFO_DMACHSUP_SHIFT (0x04u)
#define CSL_USB20_RAMINFO_DMACHSUP_RESETVAL (0x00u)

#define CSL_USB20_RAMINFO_RAMWIDTHBITS_MASK (0x0Fu)
#define CSL_USB20_RAMINFO_RAMWIDTHBITS_SHIFT (0x00u)
#define CSL_USB20_RAMINFO_RAMWIDTHBITS_RESETVAL (0x00u)

#define CSL_USB20_RAMINFO_RESETVAL       (0x00u)

/* VPLEN */

#define CSL_USB20_VPLEN_VBUSPULSELEN_MASK (0xFFu)
#define CSL_USB20_VPLEN_VBUSPULSELEN_SHIFT (0x00u)
#define CSL_USB20_VPLEN_VBUSPULSELEN_RESETVAL (0x00u)

#define CSL_USB20_VPLEN_RESETVAL         (0x00u)

/* TXFUNCADDR */

#define CSL_USB_TXFUNCADDR_FUNCADDR_MASK (0x7Fu)
#define CSL_USB_TXFUNCADDR_FUNCADDR_SHIFT (0x00u)
#define CSL_USB_TXFUNCADDR_FUNCADDR_RESETVAL (0x00u)

#define CSL_USB_TXFUNCADDR_RESETVAL      (0x00u)

/* TXHUBADDR */

#define CSL_USB_TXHUBADDR_MULT_TRANS_MASK (0x80u)
#define CSL_USB_TXHUBADDR_MULT_TRANS_SHIFT (0x07u)
#define CSL_USB_TXHUBADDR_MULT_TRANS_RESETVAL (0x00u)

#define CSL_USB_TXHUBADDR_HUBADDR_MASK   (0x7Fu)
#define CSL_USB_TXHUBADDR_HUBADDR_SHIFT  (0x00u)
#define CSL_USB_TXHUBADDR_HUBADDR_RESETVAL (0x00u)

#define CSL_USB_TXHUBADDR_RESETVAL       (0x00u)

/* TXHUBPORT */

#define CSL_USB_TXHUBPORT_HUBPORT_MASK   (0x7Fu)
#define CSL_USB_TXHUBPORT_HUBPORT_SHIFT  (0x00u)
#define CSL_USB_TXHUBPORT_HUBPORT_RESETVAL (0x00u)

#define CSL_USB_TXHUBPORT_RESETVAL       (0x00u)

/* RXFUNCADDR */

#define CSL_USB_RXFUNCADDR_FUNCADDR_MASK (0x7Fu)
#define CSL_USB_RXFUNCADDR_FUNCADDR_SHIFT (0x00u)
#define CSL_USB_RXFUNCADDR_FUNCADDR_RESETVAL (0x00u)

#define CSL_USB_RXFUNCADDR_RESETVAL      (0x00u)

/* RXHUBADDR */

#define CSL_USB_RXHUBADDR_MULT_TRANS_MASK (0x80u)
#define CSL_USB_RXHUBADDR_MULT_TRANS_SHIFT (0x07u)
#define CSL_USB_RXHUBADDR_MULT_TRANS_RESETVAL (0x00u)

#define CSL_USB_RXHUBADDR_HUBADDR_MASK   (0x7Fu)
#define CSL_USB_RXHUBADDR_HUBADDR_SHIFT  (0x00u)
#define CSL_USB_RXHUBADDR_HUBADDR_RESETVAL (0x00u)

#define CSL_USB_RXHUBADDR_RESETVAL       (0x00u)

/* RXHUBPORT */

#define CSL_USB_RXHUBPORT_HUBPORT_MASK   (0x7Fu)
#define CSL_USB_RXHUBPORT_HUBPORT_SHIFT  (0x00u)
#define CSL_USB_RXHUBPORT_HUBPORT_RESETVAL (0x00u)

#define CSL_USB_RXHUBPORT_RESETVAL       (0x00u)

/* TXMAXP */

#define CSL_USB_TXMAXP_MAXPAYLOAD_MASK   (0x07FFu)
#define CSL_USB_TXMAXP_MAXPAYLOAD_SHIFT  (0x0000u)
#define CSL_USB_TXMAXP_MAXPAYLOAD_RESETVAL (0x0000u)

#define CSL_USB_TXMAXP_RESETVAL          (0x0000u)

/* PERI_CSR0 */

#define CSL_USB_PERI_CSR0_FLUSHFIFO_MASK (0x0100u)
#define CSL_USB_PERI_CSR0_FLUSHFIFO_SHIFT (0x0008u)
#define CSL_USB_PERI_CSR0_FLUSHFIFO_RESETVAL (0x0000u)

#define CSL_USB_PERI_CSR0_SERV_SETUPEND_MASK (0x0080u)
#define CSL_USB_PERI_CSR0_SERV_SETUPEND_SHIFT (0x0007u)
#define CSL_USB_PERI_CSR0_SERV_SETUPEND_RESETVAL (0x0000u)

#define CSL_USB_PERI_CSR0_SERV_RXPKTRDY_MASK (0x0040u)
#define CSL_USB_PERI_CSR0_SERV_RXPKTRDY_SHIFT (0x0006u)
#define CSL_USB_PERI_CSR0_SERV_RXPKTRDY_RESETVAL (0x0000u)

#define CSL_USB_PERI_CSR0_SENDSTALL_MASK (0x0020u)
#define CSL_USB_PERI_CSR0_SENDSTALL_SHIFT (0x0005u)
#define CSL_USB_PERI_CSR0_SENDSTALL_RESETVAL (0x0000u)

#define CSL_USB_PERI_CSR0_SETUPEND_MASK  (0x0010u)
#define CSL_USB_PERI_CSR0_SETUPEND_SHIFT (0x0004u)
#define CSL_USB_PERI_CSR0_SETUPEND_RESETVAL (0x0000u)

#define CSL_USB_PERI_CSR0_DATAEND_MASK   (0x0008u)
#define CSL_USB_PERI_CSR0_DATAEND_SHIFT  (0x0003u)
#define CSL_USB_PERI_CSR0_DATAEND_RESETVAL (0x0000u)

#define CSL_USB_PERI_CSR0_SENTSTALL_MASK (0x0004u)
#define CSL_USB_PERI_CSR0_SENTSTALL_SHIFT (0x0002u)
#define CSL_USB_PERI_CSR0_SENTSTALL_RESETVAL (0x0000u)

#define CSL_USB_PERI_CSR0_TXPKTRDY_MASK  (0x0002u)
#define CSL_USB_PERI_CSR0_TXPKTRDY_SHIFT (0x0001u)
#define CSL_USB_PERI_CSR0_TXPKTRDY_RESETVAL (0x0000u)

#define CSL_USB_PERI_CSR0_RXPKTRDY_MASK  (0x0001u)
#define CSL_USB_PERI_CSR0_RXPKTRDY_SHIFT (0x0000u)
#define CSL_USB_PERI_CSR0_RXPKTRDY_RESETVAL (0x0000u)

#define CSL_USB_PERI_CSR0_RESETVAL       (0x0000u)

/* HOST_CSR0 */

#define CSL_USB_HOST_CSR0_DATATOGWREN_MASK (0x0400u)
#define CSL_USB_HOST_CSR0_DATATOGWREN_SHIFT (0x000Au)
#define CSL_USB_HOST_CSR0_DATATOGWREN_RESETVAL (0x0000u)

#define CSL_USB_HOST_CSR0_DATATOG_MASK   (0x0200u)
#define CSL_USB_HOST_CSR0_DATATOG_SHIFT  (0x0009u)
#define CSL_USB_HOST_CSR0_DATATOG_RESETVAL (0x0000u)

#define CSL_USB_HOST_CSR0_FLUSHFIFO_MASK (0x0100u)
#define CSL_USB_HOST_CSR0_FLUSHFIFO_SHIFT (0x0008u)
#define CSL_USB_HOST_CSR0_FLUSHFIFO_RESETVAL (0x0000u)

#define CSL_USB_HOST_CSR0_NAK_TIMEOUT_MASK (0x0080u)
#define CSL_USB_HOST_CSR0_NAK_TIMEOUT_SHIFT (0x0007u)
#define CSL_USB_HOST_CSR0_NAK_TIMEOUT_RESETVAL (0x0000u)

#define CSL_USB_HOST_CSR0_STATUSPKT_MASK (0x0040u)
#define CSL_USB_HOST_CSR0_STATUSPKT_SHIFT (0x0006u)
#define CSL_USB_HOST_CSR0_STATUSPKT_RESETVAL (0x0000u)

#define CSL_USB_HOST_CSR0_REQPKT_MASK    (0x0020u)
#define CSL_USB_HOST_CSR0_REQPKT_SHIFT   (0x0005u)
#define CSL_USB_HOST_CSR0_REQPKT_RESETVAL (0x0000u)

#define CSL_USB_HOST_CSR0_ERROR_MASK     (0x0010u)
#define CSL_USB_HOST_CSR0_ERROR_SHIFT    (0x0004u)
#define CSL_USB_HOST_CSR0_ERROR_RESETVAL (0x0000u)

#define CSL_USB_HOST_CSR0_SETUPPKT_MASK  (0x0008u)
#define CSL_USB_HOST_CSR0_SETUPPKT_SHIFT (0x0003u)
#define CSL_USB_HOST_CSR0_SETUPPKT_RESETVAL (0x0000u)

#define CSL_USB_HOST_CSR0_RXSTALL_MASK   (0x0004u)
#define CSL_USB_HOST_CSR0_RXSTALL_SHIFT  (0x0002u)
#define CSL_USB_HOST_CSR0_RXSTALL_RESETVAL (0x0000u)

#define CSL_USB_HOST_CSR0_TXPKTRDY_MASK  (0x0002u)
#define CSL_USB_HOST_CSR0_TXPKTRDY_SHIFT (0x0001u)
#define CSL_USB_HOST_CSR0_TXPKTRDY_RESETVAL (0x0000u)

#define CSL_USB_HOST_CSR0_RXPKTRDY_MASK  (0x0001u)
#define CSL_USB_HOST_CSR0_RXPKTRDY_SHIFT (0x0000u)
#define CSL_USB_HOST_CSR0_RXPKTRDY_RESETVAL (0x0000u)

#define CSL_USB_HOST_CSR0_RESETVAL       (0x0000u)

/* PERI_TXCSR */

#define CSL_USB_PERI_TXCSR_AUTOSET_MASK  (0x8000u)
#define CSL_USB_PERI_TXCSR_AUTOSET_SHIFT (0x000Fu)
#define CSL_USB_PERI_TXCSR_AUTOSET_RESETVAL (0x0000u)

#define CSL_USB_PERI_TXCSR_ISO_MASK      (0x4000u)
#define CSL_USB_PERI_TXCSR_ISO_SHIFT     (0x000Eu)
#define CSL_USB_PERI_TXCSR_ISO_RESETVAL  (0x0000u)

#define CSL_USB_PERI_TXCSR_MODE_MASK     (0x2000u)
#define CSL_USB_PERI_TXCSR_MODE_SHIFT    (0x000Du)
#define CSL_USB_PERI_TXCSR_MODE_RESETVAL (0x0000u)

#define CSL_USB_PERI_TXCSR_DMAEN_MASK    (0x1000u)
#define CSL_USB_PERI_TXCSR_DMAEN_SHIFT   (0x000Cu)
#define CSL_USB_PERI_TXCSR_DMAEN_RESETVAL (0x0000u)

#define CSL_USB_PERI_TXCSR_FRCDATATOG_MASK (0x0800u)
#define CSL_USB_PERI_TXCSR_FRCDATATOG_SHIFT (0x000Bu)
#define CSL_USB_PERI_TXCSR_FRCDATATOG_RESETVAL (0x0000u)

#define CSL_USB_PERI_TXCSR_DMAMODE_MASK  (0x0400u)
#define CSL_USB_PERI_TXCSR_DMAMODE_SHIFT (0x000Au)
#define CSL_USB_PERI_TXCSR_DMAMODE_RESETVAL (0x0000u)

#define CSL_USB_PERI_TXCSR_CLRDATATOG_MASK (0x0040u)
#define CSL_USB_PERI_TXCSR_CLRDATATOG_SHIFT (0x0006u)
#define CSL_USB_PERI_TXCSR_CLRDATATOG_RESETVAL (0x0000u)

#define CSL_USB_PERI_TXCSR_SENTSTALL_MASK (0x0020u)
#define CSL_USB_PERI_TXCSR_SENTSTALL_SHIFT (0x0005u)
#define CSL_USB_PERI_TXCSR_SENTSTALL_RESETVAL (0x0000u)

#define CSL_USB_PERI_TXCSR_SENDSTALL_MASK (0x0010u)
#define CSL_USB_PERI_TXCSR_SENDSTALL_SHIFT (0x0004u)
#define CSL_USB_PERI_TXCSR_SENDSTALL_RESETVAL (0x0000u)

#define CSL_USB_PERI_TXCSR_FLUSHFIFO_MASK (0x0008u)
#define CSL_USB_PERI_TXCSR_FLUSHFIFO_SHIFT (0x0003u)
#define CSL_USB_PERI_TXCSR_FLUSHFIFO_RESETVAL (0x0000u)

#define CSL_USB_PERI_TXCSR_UNDERRUN_MASK (0x0004u)
#define CSL_USB_PERI_TXCSR_UNDERRUN_SHIFT (0x0002u)
#define CSL_USB_PERI_TXCSR_UNDERRUN_RESETVAL (0x0000u)

#define CSL_USB_PERI_TXCSR_FIFONOTEMPTY_MASK (0x0002u)
#define CSL_USB_PERI_TXCSR_FIFONOTEMPTY_SHIFT (0x0001u)
#define CSL_USB_PERI_TXCSR_FIFONOTEMPTY_RESETVAL (0x0000u)

#define CSL_USB_PERI_TXCSR_TXPKTRDY_MASK (0x0001u)
#define CSL_USB_PERI_TXCSR_TXPKTRDY_SHIFT (0x0000u)
#define CSL_USB_PERI_TXCSR_TXPKTRDY_RESETVAL (0x0000u)

#define CSL_USB_PERI_TXCSR_RESETVAL      (0x0000u)

/* HOST_TXCSR */

#define CSL_USB_HOST_TXCSR_AUTOSET_MASK  (0x8000u)
#define CSL_USB_HOST_TXCSR_AUTOSET_SHIFT (0x000Fu)
#define CSL_USB_HOST_TXCSR_AUTOSET_RESETVAL (0x0000u)

#define CSL_USB_HOST_TXCSR_MODE_MASK     (0x2000u)
#define CSL_USB_HOST_TXCSR_MODE_SHIFT    (0x000Du)
#define CSL_USB_HOST_TXCSR_MODE_RESETVAL (0x0000u)

#define CSL_USB_HOST_TXCSR_DMAEN_MASK    (0x1000u)
#define CSL_USB_HOST_TXCSR_DMAEN_SHIFT   (0x000Cu)
#define CSL_USB_HOST_TXCSR_DMAEN_RESETVAL (0x0000u)

#define CSL_USB_HOST_TXCSR_FRCDATATOG_MASK (0x0800u)
#define CSL_USB_HOST_TXCSR_FRCDATATOG_SHIFT (0x000Bu)
#define CSL_USB_HOST_TXCSR_FRCDATATOG_RESETVAL (0x0000u)

#define CSL_USB_HOST_TXCSR_DMAMODE_MASK  (0x0400u)
#define CSL_USB_HOST_TXCSR_DMAMODE_SHIFT (0x000Au)
#define CSL_USB_HOST_TXCSR_DMAMODE_RESETVAL (0x0000u)

#define CSL_USB_HOST_TXCSR_DATATOGWREN_MASK (0x0200u)
#define CSL_USB_HOST_TXCSR_DATATOGWREN_SHIFT (0x0009u)
#define CSL_USB_HOST_TXCSR_DATATOGWREN_RESETVAL (0x0000u)

#define CSL_USB_HOST_TXCSR_DATATOG_MASK  (0x0100u)
#define CSL_USB_HOST_TXCSR_DATATOG_SHIFT (0x0008u)
#define CSL_USB_HOST_TXCSR_DATATOG_RESETVAL (0x0000u)

#define CSL_USB_HOST_TXCSR_NAK_TIMEOUT_MASK (0x0080u)
#define CSL_USB_HOST_TXCSR_NAK_TIMEOUT_SHIFT (0x0007u)
#define CSL_USB_HOST_TXCSR_NAK_TIMEOUT_RESETVAL (0x0000u)

#define CSL_USB_HOST_TXCSR_CLRDATATOG_MASK (0x0040u)
#define CSL_USB_HOST_TXCSR_CLRDATATOG_SHIFT (0x0006u)
#define CSL_USB_HOST_TXCSR_CLRDATATOG_RESETVAL (0x0000u)

#define CSL_USB_HOST_TXCSR_RXSTALL_MASK  (0x0020u)
#define CSL_USB_HOST_TXCSR_RXSTALL_SHIFT (0x0005u)
#define CSL_USB_HOST_TXCSR_RXSTALL_RESETVAL (0x0000u)

#define CSL_USB_HOST_TXCSR_SETUPPKT_MASK (0x0010u)
#define CSL_USB_HOST_TXCSR_SETUPPKT_SHIFT (0x0004u)
#define CSL_USB_HOST_TXCSR_SETUPPKT_RESETVAL (0x0000u)

#define CSL_USB_HOST_TXCSR_FLUSHFIFO_MASK (0x0008u)
#define CSL_USB_HOST_TXCSR_FLUSHFIFO_SHIFT (0x0003u)
#define CSL_USB_HOST_TXCSR_FLUSHFIFO_RESETVAL (0x0000u)

#define CSL_USB_HOST_TXCSR_ERROR_MASK    (0x0004u)
#define CSL_USB_HOST_TXCSR_ERROR_SHIFT   (0x0002u)
#define CSL_USB_HOST_TXCSR_ERROR_RESETVAL (0x0000u)

#define CSL_USB_HOST_TXCSR_FIFONOTEMPTY_MASK (0x0002u)
#define CSL_USB_HOST_TXCSR_FIFONOTEMPTY_SHIFT (0x0001u)
#define CSL_USB_HOST_TXCSR_FIFONOTEMPTY_RESETVAL (0x0000u)

#define CSL_USB_HOST_TXCSR_TXPKTRDY_MASK (0x0001u)
#define CSL_USB_HOST_TXCSR_TXPKTRDY_SHIFT (0x0000u)
#define CSL_USB_HOST_TXCSR_TXPKTRDY_RESETVAL (0x0000u)

#define CSL_USB_HOST_TXCSR_RESETVAL      (0x0000u)

/* RXMAXP */

#define CSL_USB_RXMAXP_MAXPAYLOAD_MASK   (0x07FFu)
#define CSL_USB_RXMAXP_MAXPAYLOAD_SHIFT  (0x0000u)
#define CSL_USB_RXMAXP_MAXPAYLOAD_RESETVAL (0x0000u)

#define CSL_USB_RXMAXP_RESETVAL          (0x0000u)

/* PERI_RXCSR */

#define CSL_USB_PERI_RXCSR_AUTOCLEAR_MASK (0x8000u)
#define CSL_USB_PERI_RXCSR_AUTOCLEAR_SHIFT (0x000Fu)
#define CSL_USB_PERI_RXCSR_AUTOCLEAR_RESETVAL (0x0000u)

#define CSL_USB_PERI_RXCSR_ISO_MASK      (0x4000u)
#define CSL_USB_PERI_RXCSR_ISO_SHIFT     (0x000Eu)
#define CSL_USB_PERI_RXCSR_ISO_RESETVAL  (0x0000u)

#define CSL_USB_PERI_RXCSR_DMAEN_MASK    (0x2000u)
#define CSL_USB_PERI_RXCSR_DMAEN_SHIFT   (0x000Du)
#define CSL_USB_PERI_RXCSR_DMAEN_RESETVAL (0x0000u)

#define CSL_USB_PERI_RXCSR_DISNYET_MASK  (0x1000u)
#define CSL_USB_PERI_RXCSR_DISNYET_SHIFT (0x000Cu)
#define CSL_USB_PERI_RXCSR_DISNYET_RESETVAL (0x0000u)

#define CSL_USB_PERI_RXCSR_DMAMODE_MASK  (0x0800u)
#define CSL_USB_PERI_RXCSR_DMAMODE_SHIFT (0x000Bu)
#define CSL_USB_PERI_RXCSR_DMAMODE_RESETVAL (0x0000u)

#define CSL_USB_PERI_RXCSR_CLRDATATOG_MASK (0x0080u)
#define CSL_USB_PERI_RXCSR_CLRDATATOG_SHIFT (0x0007u)
#define CSL_USB_PERI_RXCSR_CLRDATATOG_RESETVAL (0x0000u)

#define CSL_USB_PERI_RXCSR_SENTSTALL_MASK (0x0040u)
#define CSL_USB_PERI_RXCSR_SENTSTALL_SHIFT (0x0006u)
#define CSL_USB_PERI_RXCSR_SENTSTALL_RESETVAL (0x0000u)

#define CSL_USB_PERI_RXCSR_SENDSTALL_MASK (0x0020u)
#define CSL_USB_PERI_RXCSR_SENDSTALL_SHIFT (0x0005u)
#define CSL_USB_PERI_RXCSR_SENDSTALL_RESETVAL (0x0000u)

#define CSL_USB_PERI_RXCSR_FLUSHFIFO_MASK (0x0010u)
#define CSL_USB_PERI_RXCSR_FLUSHFIFO_SHIFT (0x0004u)
#define CSL_USB_PERI_RXCSR_FLUSHFIFO_RESETVAL (0x0000u)

#define CSL_USB_PERI_RXCSR_DATAERROR_MASK (0x0008u)
#define CSL_USB_PERI_RXCSR_DATAERROR_SHIFT (0x0003u)
#define CSL_USB_PERI_RXCSR_DATAERROR_RESETVAL (0x0000u)

#define CSL_USB_PERI_RXCSR_OVERRUN_MASK  (0x0004u)
#define CSL_USB_PERI_RXCSR_OVERRUN_SHIFT (0x0002u)
#define CSL_USB_PERI_RXCSR_OVERRUN_RESETVAL (0x0000u)

#define CSL_USB_PERI_RXCSR_FIFOFULL_MASK (0x0002u)
#define CSL_USB_PERI_RXCSR_FIFOFULL_SHIFT (0x0001u)
#define CSL_USB_PERI_RXCSR_FIFOFULL_RESETVAL (0x0000u)

#define CSL_USB_PERI_RXCSR_RXPKTRDY_MASK (0x0001u)
#define CSL_USB_PERI_RXCSR_RXPKTRDY_SHIFT (0x0000u)
#define CSL_USB_PERI_RXCSR_RXPKTRDY_RESETVAL (0x0000u)

#define CSL_USB_PERI_RXCSR_RESETVAL      (0x0000u)

/* HOST_RXCSR */

#define CSL_USB_HOST_RXCSR_AUTOCLEAR_MASK (0x8000u)
#define CSL_USB_HOST_RXCSR_AUTOCLEAR_SHIFT (0x000Fu)
#define CSL_USB_HOST_RXCSR_AUTOCLEAR_RESETVAL (0x0000u)

#define CSL_USB_HOST_RXCSR_AUTOREQ_MASK  (0x4000u)
#define CSL_USB_HOST_RXCSR_AUTOREQ_SHIFT (0x000Eu)
#define CSL_USB_HOST_RXCSR_AUTOREQ_RESETVAL (0x0000u)

#define CSL_USB_HOST_RXCSR_DMAEN_MASK    (0x2000u)
#define CSL_USB_HOST_RXCSR_DMAEN_SHIFT   (0x000Du)
#define CSL_USB_HOST_RXCSR_DMAEN_RESETVAL (0x0000u)

#define CSL_USB_HOST_RXCSR_DISNYET_MASK  (0x1000u)
#define CSL_USB_HOST_RXCSR_DISNYET_SHIFT (0x000Cu)
#define CSL_USB_HOST_RXCSR_DISNYET_RESETVAL (0x0000u)

#define CSL_USB_HOST_RXCSR_DMAMODE_MASK  (0x0800u)
#define CSL_USB_HOST_RXCSR_DMAMODE_SHIFT (0x000Bu)
#define CSL_USB_HOST_RXCSR_DMAMODE_RESETVAL (0x0000u)

#define CSL_USB_HOST_RXCSR_DATATOGWREN_MASK (0x0400u)
#define CSL_USB_HOST_RXCSR_DATATOGWREN_SHIFT (0x000Au)
#define CSL_USB_HOST_RXCSR_DATATOGWREN_RESETVAL (0x0000u)

#define CSL_USB_HOST_RXCSR_DATATOG_MASK  (0x0200u)
#define CSL_USB_HOST_RXCSR_DATATOG_SHIFT (0x0009u)
#define CSL_USB_HOST_RXCSR_DATATOG_RESETVAL (0x0000u)

#define CSL_USB_HOST_RXCSR_CLRDATATOG_MASK (0x0080u)
#define CSL_USB_HOST_RXCSR_CLRDATATOG_SHIFT (0x0007u)
#define CSL_USB_HOST_RXCSR_CLRDATATOG_RESETVAL (0x0000u)

#define CSL_USB_HOST_RXCSR_RXSTALL_MASK  (0x0040u)
#define CSL_USB_HOST_RXCSR_RXSTALL_SHIFT (0x0006u)
#define CSL_USB_HOST_RXCSR_RXSTALL_RESETVAL (0x0000u)

#define CSL_USB_HOST_RXCSR_REQPKT_MASK   (0x0020u)
#define CSL_USB_HOST_RXCSR_REQPKT_SHIFT  (0x0005u)
#define CSL_USB_HOST_RXCSR_REQPKT_RESETVAL (0x0000u)

#define CSL_USB_HOST_RXCSR_FLUSHFIFO_MASK (0x0010u)
#define CSL_USB_HOST_RXCSR_FLUSHFIFO_SHIFT (0x0004u)
#define CSL_USB_HOST_RXCSR_FLUSHFIFO_RESETVAL (0x0000u)

#define CSL_USB_HOST_RXCSR_DATAERR_NAKTIMEOUT_MASK (0x0008u)
#define CSL_USB_HOST_RXCSR_DATAERR_NAKTIMEOUT_SHIFT (0x0003u)
#define CSL_USB_HOST_RXCSR_DATAERR_NAKTIMEOUT_RESETVAL (0x0000u)

#define CSL_USB_HOST_RXCSR_ERROR_MASK    (0x0004u)
#define CSL_USB_HOST_RXCSR_ERROR_SHIFT   (0x0002u)
#define CSL_USB_HOST_RXCSR_ERROR_RESETVAL (0x0000u)

#define CSL_USB_HOST_RXCSR_FIFOFULL_MASK (0x0002u)
#define CSL_USB_HOST_RXCSR_FIFOFULL_SHIFT (0x0001u)
#define CSL_USB_HOST_RXCSR_FIFOFULL_RESETVAL (0x0000u)

#define CSL_USB_HOST_RXCSR_RXPKTRDY_MASK (0x0001u)
#define CSL_USB_HOST_RXCSR_RXPKTRDY_SHIFT (0x0000u)
#define CSL_USB_HOST_RXCSR_RXPKTRDY_RESETVAL (0x0000u)

#define CSL_USB_HOST_RXCSR_RESETVAL      (0x0000u)

/* COUNT0 */

#define CSL_USB_COUNT0_EP0RXCOUNT_MASK   (0x007Fu)
#define CSL_USB_COUNT0_EP0RXCOUNT_SHIFT  (0x0000u)
#define CSL_USB_COUNT0_EP0RXCOUNT_RESETVAL (0x0000u)

#define CSL_USB_COUNT0_RESETVAL          (0x0000u)

/* RXCOUNT */

#define CSL_USB_RXCOUNT_EPRXCOUNT_MASK   (0x1FFFu)
#define CSL_USB_RXCOUNT_EPRXCOUNT_SHIFT  (0x0000u)
#define CSL_USB_RXCOUNT_EPRXCOUNT_RESETVAL (0x0000u)

#define CSL_USB_RXCOUNT_RESETVAL         (0x0000u)

/* HOST_TYPE0 */

#define CSL_USB_HOST_TYPE0_SPEED_MASK    (0xC0u)
#define CSL_USB_HOST_TYPE0_SPEED_SHIFT   (0x06u)
#define CSL_USB_HOST_TYPE0_SPEED_RESETVAL (0x00u)

#define CSL_USB_HOST_TYPE0_RESETVAL      (0x00u)

/* HOST_TXTYPE */

#define CSL_USB_HOST_TXTYPE_SPEED_MASK   (0xC0u)
#define CSL_USB_HOST_TXTYPE_SPEED_SHIFT  (0x06u)
#define CSL_USB_HOST_TXTYPE_SPEED_RESETVAL (0x00u)

#define CSL_USB_HOST_TXTYPE_PROT_MASK    (0x30u)
#define CSL_USB_HOST_TXTYPE_PROT_SHIFT   (0x04u)
#define CSL_USB_HOST_TXTYPE_PROT_RESETVAL (0x00u)

#define CSL_USB_HOST_TXTYPE_TENDPN_MASK  (0x0Fu)
#define CSL_USB_HOST_TXTYPE_TENDPN_SHIFT (0x00u)
#define CSL_USB_HOST_TXTYPE_TENDPN_RESETVAL (0x00u)

#define CSL_USB_HOST_TXTYPE_RESETVAL     (0x00u)

/* HOST_NAKLIMIT0 */

#define CSL_USB_HOST_NAKLIMIT0_EP0NAKLIMIT_MASK (0x1Fu)
#define CSL_USB_HOST_NAKLIMIT0_EP0NAKLIMIT_SHIFT (0x00u)
#define CSL_USB_HOST_NAKLIMIT0_EP0NAKLIMIT_RESETVAL (0x00u)

#define CSL_USB_HOST_NAKLIMIT0_RESETVAL  (0x00u)

/* HOST_TXINTERVAL */

#define CSL_USB_HOST_TXINTERVAL_POLINTVL_NAKLIMIT_MASK (0xFFu)
#define CSL_USB_HOST_TXINTERVAL_POLINTVL_NAKLIMIT_SHIFT (0x00u)
#define CSL_USB_HOST_TXINTERVAL_POLINTVL_NAKLIMIT_RESETVAL (0x00u)

#define CSL_USB_HOST_TXINTERVAL_RESETVAL (0x00u)

/* HOST_RXTYPE */

#define CSL_USB_HOST_RXTYPE_SPEED_MASK   (0xC0u)
#define CSL_USB_HOST_RXTYPE_SPEED_SHIFT  (0x06u)
#define CSL_USB_HOST_RXTYPE_SPEED_RESETVAL (0x00u)

#define CSL_USB_HOST_RXTYPE_PROT_MASK    (0x30u)
#define CSL_USB_HOST_RXTYPE_PROT_SHIFT   (0x04u)
#define CSL_USB_HOST_RXTYPE_PROT_RESETVAL (0x00u)

#define CSL_USB_HOST_RXTYPE_RENDPN_MASK  (0x0Fu)
#define CSL_USB_HOST_RXTYPE_RENDPN_SHIFT (0x00u)
#define CSL_USB_HOST_RXTYPE_RENDPN_RESETVAL (0x00u)

#define CSL_USB_HOST_RXTYPE_RESETVAL     (0x00u)

/* HOST_RXINTERVAL */

#define CSL_USB_HOST_RXINTERVAL_POLINTVL_NAKLIMIT_MASK (0xFFu)
#define CSL_USB_HOST_RXINTERVAL_POLINTVL_NAKLIMIT_SHIFT (0x00u)
#define CSL_USB_HOST_RXINTERVAL_POLINTVL_NAKLIMIT_RESETVAL (0x00u)

#define CSL_USB_HOST_RXINTERVAL_RESETVAL (0x00u)

/* CONFIGDATA */

#define CSL_USB_CONFIGDATA_MPRXE_MASK    (0x80u)
#define CSL_USB_CONFIGDATA_MPRXE_SHIFT   (0x07u)
#define CSL_USB_CONFIGDATA_MPRXE_RESETVAL (0x00u)

#define CSL_USB_CONFIGDATA_MPTXE_MASK    (0x40u)
#define CSL_USB_CONFIGDATA_MPTXE_SHIFT   (0x06u)
#define CSL_USB_CONFIGDATA_MPTXE_RESETVAL (0x00u)

#define CSL_USB_CONFIGDATA_BIGENDIAN_MASK (0x20u)
#define CSL_USB_CONFIGDATA_BIGENDIAN_SHIFT (0x05u)
#define CSL_USB_CONFIGDATA_BIGENDIAN_RESETVAL (0x00u)

#define CSL_USB_CONFIGDATA_HBRXE_MASK    (0x10u)
#define CSL_USB_CONFIGDATA_HBRXE_SHIFT   (0x04u)
#define CSL_USB_CONFIGDATA_HBRXE_RESETVAL (0x00u)

#define CSL_USB_CONFIGDATA_HBTXE_MASK    (0x08u)
#define CSL_USB_CONFIGDATA_HBTXE_SHIFT   (0x03u)
#define CSL_USB_CONFIGDATA_HBTXE_RESETVAL (0x00u)

#define CSL_USB_CONFIGDATA_DYNFIFO_MASK  (0x04u)
#define CSL_USB_CONFIGDATA_DYNFIFO_SHIFT (0x02u)
#define CSL_USB_CONFIGDATA_DYNFIFO_RESETVAL (0x00u)

#define CSL_USB_CONFIGDATA_SOFTCONE_MASK (0x02u)
#define CSL_USB_CONFIGDATA_SOFTCONE_SHIFT (0x01u)
#define CSL_USB_CONFIGDATA_SOFTCONE_RESETVAL (0x00u)

#define CSL_USB_CONFIGDATA_UTMIDATAWIDTH_MASK (0x01u)
#define CSL_USB_CONFIGDATA_UTMIDATAWIDTH_SHIFT (0x00u)
#define CSL_USB_CONFIGDATA_UTMIDATAWIDTH_RESETVAL (0x00u)

#define CSL_USB_CONFIGDATA_RESETVAL      (0x00u)

/* FIFOSIZE */

#define CSL_USB_FIFOSIZE_RXFIFOSZ_MASK   (0xF0u)
#define CSL_USB_FIFOSIZE_RXFIFOSZ_SHIFT  (0x04u)
#define CSL_USB_FIFOSIZE_RXFIFOSZ_RESETVAL (0x00u)

#define CSL_USB_FIFOSIZE_TXFIFOSZ_MASK   (0x0Fu)
#define CSL_USB_FIFOSIZE_TXFIFOSZ_SHIFT  (0x00u)
#define CSL_USB_FIFOSIZE_TXFIFOSZ_RESETVAL (0x00u)

#define CSL_USB_FIFOSIZE_RESETVAL        (0x00u)

#endif
/* Rev.No.   Date/Time               ECN No.          Modifier      */
/* -------   ---------               -------          --------      */

/* 5         17 Jan 2005 14:57:18    5978             xkeshavm      */
/*                                                                  */
/* uploaded cslr_usb_001.h after changes as per Kevin^s mail        */
/********************************************************************/
