#ifndef __SW_JPEG_OVERLAY_FILTER_H__
#define __SW_JPEG_OVERLAY_FILTER_H__
#include "SWMessage.h"
#include "SWYUVOverlayFilter.h"

class CSWJPEGOverlayFilter : public CSWYUVOverlayFilter,CSWMessage
{
	CLASSINFO(CSWJPEGOverlayFilter, CSWYUVOverlayFilter)
public:
	CSWJPEGOverlayFilter();
	virtual ~CSWJPEGOverlayFilter();
protected:
	virtual HRESULT Receive(CSWObject* obj);
	HRESULT OnOverlayProcess(WPARAM wParam, LPARAM lParam);
	HRESULT OnOverlayDoProcess(WPARAM wParam, LPARAM lParam);
	HRESULT OnOSDGetJPEGEnable(WPARAM wParam, LPARAM lParam);
	HRESULT OnOSDGetJPEGPlateEnable(WPARAM wParam, LPARAM lParam);
	HRESULT OnOSDGetJPEGTimeEnable(WPARAM wParam, LPARAM lParam);
	HRESULT OnOSDGetJPEGText(WPARAM wParam, LPARAM lParam);
	HRESULT OnOSDGetJPEGFontSize(WPARAM wParam, LPARAM lParam);
	HRESULT OnOSDGetJPEGFontRBG(WPARAM wParam, LPARAM lParam);
	HRESULT OnOSDGetJPEGPox(WPARAM wParam, LPARAM lParam);
	HRESULT OnOSDSetJPEGEnable(WPARAM wParam, LPARAM lParam);
	HRESULT OnOSDSetJPEGPlateEnable(WPARAM wParam, LPARAM lParam);
	HRESULT OnOSDSetJPEGTimeEnable(WPARAM wParam, LPARAM lParam);
	HRESULT OnOSDSetJPEGText(WPARAM wParam, LPARAM lParam);
	HRESULT OnOSDSetJPEGFontSize(WPARAM wParam, LPARAM lParam);
	HRESULT OnOSDSetJPEGFontRBG(WPARAM wParam, LPARAM lParam);
	HRESULT OnOSDSetJPEGPox(WPARAM wParam, LPARAM lParam);
	HRESULT OnOSDGetDebugJPEGStatus(WPARAM wParam, LPARAM lParam);
	HRESULT OnOSDSetDebugJPEGStatus(WPARAM wParam, LPARAM lParam);
	HRESULT OnOSDSetMJPEGOverlay(WPARAM wParam, LPARAM lParam);
	HRESULT LineOverlay(SW_COMPONENT_IMAGE& img, SW_POINT& sPointA, SW_POINT& sPointB);
	HRESULT PolygonOverlay(CSWPosImage* pPosImage);

protected:
	//消息映射宏
	SW_BEGIN_MESSAGE_MAP(CSWJPEGOverlayFilter, CSWMessage)
		SW_MESSAGE_HANDLER(MSG_OVERLAY_PROCESS,           OnOverlayProcess)
		SW_MESSAGE_HANDLER(MSG_OVERLAY_DOPROCESS,	  OnOverlayDoProcess)
    SW_MESSAGE_HANDLER(MSG_OSD_GET_JPEG_ENABLE,       OnOSDGetJPEGEnable)
    SW_MESSAGE_HANDLER(MSG_OSD_GET_JPEG_PLATE_ENABLE, OnOSDGetJPEGPlateEnable)
    SW_MESSAGE_HANDLER(MSG_OSD_GET_JPEG_TIME_ENABLE,  OnOSDGetJPEGTimeEnable)
    SW_MESSAGE_HANDLER(MSG_OSD_GET_JPEG_TEXT,         OnOSDGetJPEGText)
    SW_MESSAGE_HANDLER(MSG_OSD_GET_JPEG_FONNTSIZE,    OnOSDGetJPEGFontSize)
    SW_MESSAGE_HANDLER(MSG_OSD_GET_JPEG_FONT_RBG,     OnOSDGetJPEGFontRBG)
    SW_MESSAGE_HANDLER(MSG_OSD_GET_JPEG_POX,          OnOSDGetJPEGPox)
    SW_MESSAGE_HANDLER(MSG_OSD_SET_JPEG_ENABLE,       OnOSDSetJPEGEnable)
    SW_MESSAGE_HANDLER(MSG_OSD_SET_JPEG_PLATE_ENABLE, OnOSDSetJPEGPlateEnable)
    SW_MESSAGE_HANDLER(MSG_OSD_SET_JPEG_TIME_ENABLE,  OnOSDSetJPEGTimeEnable)
    SW_MESSAGE_HANDLER(MSG_OSD_SET_JPEG_TEXT,         OnOSDSetJPEGText)
    SW_MESSAGE_HANDLER(MSG_OSD_SET_JPEG_FONNTSIZE,    OnOSDSetJPEGFontSize)
    SW_MESSAGE_HANDLER(MSG_OSD_SET_JPEG_FONT_RBG,     OnOSDSetJPEGFontRBG)
    SW_MESSAGE_HANDLER(MSG_OSD_SET_JPEG_POX,          OnOSDSetJPEGPox)
    SW_MESSAGE_HANDLER(MSG_GET_DEBUG_JPEG_STATUS,     OnOSDGetDebugJPEGStatus)
    SW_MESSAGE_HANDLER(MSG_SET_DEBUG_JPEG_STATUS,     OnOSDSetDebugJPEGStatus)
	SW_MESSAGE_HANDLER(MSG_OSD_ENABLE_JPEG_PTZ_OVERLAY,	  OnOSDEnablePTZOverlay)
	SW_MESSAGE_HANDLER(MSG_OSD_SET_JPEG_DOMEINFO_OVERLAY,	  OnOSDSetDomeInfoOverlay)
	SW_MESSAGE_HANDLER(MSG_OSD_SET_MJPEG_OVERLAY,OnOSDSetMJPEGOverlay)
	SW_MESSAGE_HANDLER(MSG_OSD_SET_JPEG_DEV_ID, OnOSDSetDevID)
	SW_END_MESSAGE_MAP()
private:
	CSWMutex  m_cMutex;
	BOOL      m_fDebug;	
	BOOL 	  m_fMJPEGDoStrOverlay;		//MJPEG流字符叠加，使用默认叠加数据，为方便上位机观察叠加效果
};
REGISTER_CLASS(CSWJPEGOverlayFilter)
#endif
