#if !defined(AFX_VCPEN_H__B065AA6A_DCF8_4A56_A5C1_445C59DE2C5A__INCLUDED_)
#define AFX_VCPEN_H__B065AA6A_DCF8_4A56_A5C1_445C59DE2C5A__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CVcColor;

/////////////////////////////////////////////////////////////////////////////
// CVcPen wrapper class

class CVcPen : public COleDispatchDriver
{
public:
	CVcPen() {}		// Calls COleDispatchDriver default constructor
	CVcPen(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CVcPen(const CVcPen& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetStyle();
	void SetStyle(long nNewValue);
	long GetJoin();
	void SetJoin(long nNewValue);
	long GetCap();
	void SetCap(long nNewValue);
	CVcColor GetVtColor();
	float GetWidth();
	void SetWidth(float newValue);
	float GetLimit();
	void SetLimit(float newValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_VCPEN_H__B065AA6A_DCF8_4A56_A5C1_445C59DE2C5A__INCLUDED_)
