//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by HvDeviceNewTest.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDS_ABOUTBOX                    101
#define IDD_HVDEVICENEWTEST_DIALOG      102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG1                     129
#define IDD_DIALOG2                     130
#define IDD_DIALOG3                     131
#define IDD_DIALOG4                     132
#define IDD_DIALOG5                     133
#define IDD_DIALOG6                     134
#define IDD_DIALOG7                     135
#define IDD_DIALOG8                     136
#define IDD_HVNAVI                      137
#define IDD_DIALOG9                     139
#define IDD_DIALOG10                    140
#define IDD_DIALOG_SETIP                142
#define IDD_DIALOG13                    148
#define IDD_AUTOLINK_DEMO_DIALOG        149
#define IDD_DIALOG12                    151
#define IDD_DIALOG14                    152
#define IDC_LIST1                       1000
#define IDC_BUTTON1                     1001
#define IDC_BUTTON2                     1002
#define IDC_EDIT1                       1002
#define IDC_BUTTON3                     1003
#define IDC_STATIC_BEST                 1003
#define IDC_EDIT9                       1003
#define IDC_BUTTON4                     1004
#define IDC_STATIC_LAST                 1004
#define IDC_EDIT10                      1004
#define IDC_STATIC_SMALL                1005
#define IDC_BUTTON8                     1005
#define IDC_EDIT11                      1005
#define IDC_STATIC_BINARY               1006
#define IDC_BUTTON9                     1006
#define IDC_EDIT12                      1006
#define IDC_FIND_DIR                    1006
#define IDC_STATIC_PLATE                1007
#define IDC_BUTTON10                    1007
#define IDC_EDIT13                      1007
#define IDC_DIR                         1007
#define IDC_BUTTON5                     1008
#define IDC_EDIT14                      1008
#define IDC_PROGRESS1                   1008
#define IDC_BUTTON6                     1009
#define IDC_BUTTON13                    1009
#define IDC_EDIT15                      1009
#define ID__RECV_HISTORY_CONFIG         1009
#define IDC_BUTTON7                     1010
#define IDC_BUTTON14                    1010
#define IDC_EDIT16                      1010
#define IDD_AUTOLINK_SETHISTORY         1010
#define IDC_STATIC_JPEG                 1011
#define IDC_BUTTON11                    1011
#define IDC_BUTTON16                    1011
#define IDC_EDIT17                      1011
#define IDR_MENU1                       1011
#define IDD_DIALOG11                    1011
#define IDC_STATIC_LPR                  1012
#define IDC_BUTTON12                    1012
#define IDC_BEGIN_TIME                  1012
#define IDC_STATIC_CAP                  1013
#define IDC_BUTTON15                    1013
#define IDC_CANCEL_BUTTON               1013
#define IDC_EDIT2                       1014
#define IDC_ENABLE_END_TIME_CHECK       1014
#define IDC_EDIT3                       1015
#define IDC_BUTTON17                    1015
#define IDC_ENABLE_HISTORY_CHECK        1015
#define IDC_EDIT4                       1016
#define IDC_EDIT5                       1017
#define IDC_EDIT6                       1018
#define IDC_END_TIME                    1018
#define IDC_EDIT7                       1019
#define IDC_INDEX_EDIT                  1019
#define IDC_EDIT8                       1020
#define IDC_SAVE_BUTTON                 1020
#define IDC_STATIC_VIDEO                1021
#define IDC_EDIT_READ_ADD3              1021
#define IDC_CHECK1                      1022
#define IDC_ENABLE_ONLYVIOLATION_CHECK  1022
#define IDC_EDIT_READ_VALUE3            1022
#define IDC_COMBO1                      1023
#define IDC_CHECK2                      1023
#define IDC_IPADDRESS1                  1024
#define IDC_CHECK_READ2                 1024
#define IDC_LIST2                       1025
#define IDC_IPADDRESS2                  1025
#define IDC_CHECK_READ3                 1025
#define IDC_CHECK_READ4                 1026
#define IDC_EDIT_CHAR                   1027
#define IDC_IPADDRESS3                  1027
#define IDC_EDIT_READ_ADD4              1027
#define IDC_EDIT_RECT                   1028
#define IDC_EDIT_READ_VALUE4            1028
#define IDC_EDIT_FACE                   1029
#define IDC_EDIT_RECT2                  1029
#define DC_EDIT_FACE                    1029
#define IDC_CHECK_READ5                 1029
#define IDC_BUTTON18                    1030
#define IDC_EDIT_READ_ADD5              1030
#define IDC_EDIT_READ_VALUE5            1031
#define IDC_CHECK_READ6                 1032
#define IDC_RADIO1                      1033
#define IDC_EDIT_READ_ADD6              1033
#define IDC_RADIO2                      1034
#define IDC_EDIT_READ_VALUE6            1034
#define IDC_CHECK_READ7                 1035
#define IDC_EDIT_READ_ADD7              1036
#define IDC_RADIO3                      1037
#define IDC_EDIT_READ_VALUE7            1037
#define IDC_RADIO4                      1038
#define IDC_CHECK_WRITE1                1038
#define IDC_EDIT_WRITE_ADD1             1039
#define IDC_EDIT_WRITE_VALUE1           1040
#define IDC_CHECK_WRITE2                1041
#define IDC_BUTTON19                    1042
#define IDC_BTN_PRTSCR                  1042
#define IDC_BUTTONHVAPI_SetRedLightRect 1042
#define IDC_BUTTON_ADD_STATIC_IP        1042
#define IDC_BTN_CAP                     1043
#define IDC_EDIT_WRITE_ADD2             1043
#define IDC_EDIT_WRITE_VALUE2           1044
#define IDC_CHECK_WRITE3                1045
#define IDC_TREE1                       1046
#define IDC_EDIT_WRITE_ADD3             1046
#define IDC_PARAM1                      1047
#define IDC_PARAM2                      1048
#define IDC_PARAM3                      1049
#define IDC_PARAM4                      1050
#define IDC_PARAM5                      1051
#define IDC_PARAM6                      1052
#define IDC_SetH264BitRate              1053
#define IDC_SetJpegCompressRate         1054
#define IDC_SetOSDEnable                1055
#define IDC_STATIC_STATUS               1056
#define IDC_SetOSDTimeEnable            1056
#define IDC_SetOSDPos                   1057
#define IDC_SetOSDFont                  1058
#define IDC_SetOSDText                  1059
#define IDC_SetCVBS                     1060
#define IDC_SetManualShutter            1061
#define IDC_SetManualGain               1062
#define IDC_SetAWBEnable                1063
#define IDC_SetAWBMode                  1064
#define IDC_SetManualRGB                1065
#define IDC_SetAGCEnable                1066
#define IDC_SetAGCLightBaseLine         1067
#define IDC_SetAGCParam                 1068
#define IDC_SetLUT                      1069
#define IDC_SetBrightness               1070
#define IDC_SetContrast                 1071
#define IDC_SetSharpness                1072
#define IDC_SetSaturation               1073
#define IDC_SetWDREnable                1074
#define IDC_SetWDRLevel                 1075
#define IDC_SetBLCLevel                 1076
#define IDC_SetDREMode                  1077
#define IDC_SetDREnable                 1078
#define IDC_SetDRELevel                 1079
#define IDC_SetDeNoiseEnable            1080
#define IDC_SetDeNoiseMode              1081
#define IDC_SetDeNoiseLevel             1082
#define IDC_SetFilterMode               1083
#define IDC_EDIT_WRITE_VALUE3           1084
#define IDC_SetDCIRIS                   1085
#define IDC_SetIPInfo                   1086
#define IDC_CHECK_WRITE4                1087
#define IDC_SetTime                     1088
#define IDC_SetTimeZone                 1089
#define IDC_SetNTPEnable                1090
#define IDC_SetNTPServerIP              1091
#define IDC_ResetDevice                 1092
#define IDC_RestoreDefaultParam         1093
#define IDC_RestoreFactoryParam         1094
#define IDC_SetParamEx                  1095
#define IDC_GetParamEx                  1096
#define IDC_GetDevBasicInfo             1097
#define IDC_GetRunMode                  1098
#define IDC_GetDevState                 1099
#define IDC_GetResetReport              1100
#define IDC_GetResetCount               1101
#define IDC_GetLog                      1102
#define IDC_GetCameraState              1103
#define IDC_GetCameraBasicInfo          1104
#define IDC_GetOSD                      1105
#define IDC_TriggerImage                1106
#define IDC_GetLUT                      1107
#define IDC_DoLogin                     1108
#define IDC_AddUser                     1109
#define IDC_DelUser                     1110
#define IDC_ModUser                     1111
#define IDC_GetUsers                    1112
#define IDC_GetVideoState               1113
#define IDC_SetSenseWdr                 1114
#define IDC_SetOCGate1                  1115
#define IDC_ExecCmdEx                   1116
#define IDC_EDIT_ExecCmdEx              1117
#define IDC_BUTTON_GetDevRunMode        1118
#define IDC_BUTTON_GetDevBasicInfoVenus 1119
#define IDC_BUTTON_GetDevStateVenus     1120
#define IDC_BUTTON_SetNTPServerUpdateInterval 1121
#define IDC_BUTTON_HVAPI_StartCOMCheck  1122
#define IDC_BUTTON_HVAPI_SetSharpnessEnable 1123
#define IDC_BUTTONHVAPI_ShrinkDCIRIS    1124
#define IDC_BUTTON_HVAPI_ZoomDCIRIS     1125
#define IDC_BUTTONHVAPI_GetAGCZone      1126
#define IDC_BUTTONHVAPI_SetGrayImageEnable 1127
#define IDC_BUTTONHVAPI_SetACSync       1128
#define IDC_BUTTONHVAPI_StartCameraTest 1129
#define IDC_BUTTONHVAPI_SetEnRedLightEnable 1130
#define IDC_BUTTONHVAPI_GetEnRedLightEnable 1131
#define IDC_BUTTONHVAPI_GetVideoStateVenus 1132
#define IDC_BUTTONHVAPI_GetCameraStateVenus 1133
#define IDC_BUTTONHVAPI_GetDebugJpegStatus 1134
#define IDC_BUTTONHVAPI_SetDebugJpegStatus 1135
#define IDC_BUTTONHVAPI_SetOSDPlateEnable 1136
#define IDC_BUTTONHVAPI_GetHddCheckReport 1137
#define IDC_START_HISTORY               1138
#define IDC_EDIT_WRITE_ADD4             1138
#define IDC_START_RECORD                1139
#define IDC_EDIT_WRITE_VALUE4           1139
#define IDC_BUTTONHVAPI_GetTraceRank    1140
#define IDC_BUTTONHVAPI_SetTraceRank    1141
#define IDC_BUTTONHVAPI_SetAutoJpegCompressEnable 1142
#define IDC_BUTTONHVAPI_SetOSDFontSize  1143
#define IDC_BUTTONHVAPI_SetOSDFontRGB   1144
#define IDC_BUTTONHVAPI_GetBlackBoxMessage 1145
#define IDC_CHECK_WRITE5                1146
#define IDC_EDIT_WRITE_ADD5             1147
#define IDC_EDIT_WRITE_VALUE5           1148
#define IDC_CHECK_WRITE6                1149
#define IDC_EDIT_WRITE_ADD6             1150
#define IDC_EDIT_WRITE_VALUE6           1151
#define IDC_CHECK_WRITE7                1152
#define IDC_EDIT_WRITE_ADD7             1153
#define IDC_EDIT_WRITE_VALUE7           1154
#define IDC_EDIT_READ_ADD1              1155
#define IDC_EDIT_READ_ADD2              1156
#define IDC_EDIT_READ_VALUE1            1157
#define IDC_EDIT_READ_VALUE2            1158
#define IDC_BUTTON_WRITE_FPGA           1159
#define IDC_BUTTON_READ_FPGA            1160
#define IDC_CHECK_READ1                 1161
#define IDC_BUTTON_CamSetTest           1162
#define IDC_STATIC_WRITE_RESULT1        1163
#define IDC_STATIC_WRITE_RESULT2        1164
#define IDC_STATIC_WRITE_RESULT3        1165
#define IDC_STATIC_WRITE_RESULT4        1166
#define IDC_STATIC_WRITE_RESULT5        1167
#define IDC_STATIC_WRITE_RESULT6        1168
#define IDC_STATIC_WRITE_RESULT7        1169
#define IDC_STATIC_READ_RESULT1         1170
#define IDC_STATIC_READ_RESULT2         1171
#define IDC_STATIC_READ_RESULT3         1172
#define IDC_STATIC_READ_RESULT4         1173
#define IDC_STATIC_READ_RESULT5         1174
#define IDC_STATIC_READ_RESULT6         1175
#define IDC_STATIC_READ_RESULT7         1176
#define IDC_BUTTONHVAPI_SetImageEnhancementEnable 1178
#define IDC_BUTTONHVAPI_SetGAMMAValue   1179
#define IDC_BUTTONHVAPI_SetGAMMAEnable  1180
#define IDC_BUTTONHVAPI_SetEnRedLightThreshold 1181
#define IDC_BUTTONHVAPI_GetCameraBasicInfo 1182
#define IDC_BUTTONsetacgzone            1183
#define IDC_BUTTONHVAPI_SetCtrlCplEnable 1184
#define IDC_BUTTONGetConnStatusEx       1185
#define IDC_BUTTONGetDevtypeEx          1186
#define IDC_BUTTONSetIPByMacAddr        1187
#define IDC_BUTTON_SetTimeZone          1188
#define IDC_BUTTONHVAPI_SetDeNoiseSNFEnable 1189
#define IDC_BUTTONHVAPI_SetDeNoiseTNFEnable 1190
#define IDC_BUTTONSetEdgeEnable         1191
#define IDC_SET_COLOR_                  1192
#define IDC_SET_COLOR                   1192
#define IDC_SET_2DDENOISE               1193
#define IDC_SET_2DDeNoiseValue          1194
#define IDC_BUTTON_SetAutoJpegCompressParam 1195
#define IDC_SetSharpnessEnable          1196
#define IDC_BUTTONGetRunStatusString    1197
#define IDC_BUTTONGetHDDStatus          1198
#define IDC_SetH264BitRateControl       1199
#define IDC_BUTTONGetCameraWorkState    1200
#define IDC_BUTTON_GetCameraWorkState   1201
#define IDC_SetStreamFps                1201
#define IDC_BUTTON__GetCameraWorkState  1202
#define IDC_BUTTON_testsearchex         1203
#define IDC_BUTTON_HVAPI_SetLEDSwitch   1204
#define IDC_BUTTON_GetRunStatus         1206
#define IDC_BUTTONSetTGIO               1208
#define IDC_BUTTONSetF1IO               1209
#define IDC_BUTTONSetEXPIO              1210
#define IDC_BUTTONSetALMIO              1211
#define IDC_BUTTONGetTGIO               1212
#define IDC_BUTTONGetF1IO               1213
#define IDC_BUTTONGetEXPIO              1214
#define IDC_BUTTONGetALMIO              1215
#define IDC_BUTTONSetColorGradation     1216
#define IDC_BUTTON20                    1217
#define IDC_BUTTON_GETIMAGE             1217
#define IDC_BUTTON_CAPTUEIMAGE          1217
#define IDC_BUTTONSetVedioRequestControl 1218
#define IDC_BUTTONHVAPI_SetAEScene      1219
#define IDC_BUTTONHVAPI_GetAEScene      1220
#define IDC_BUTTONSetDevName            1221
#define IDC_BUTTONGetDevName            1222
#define IDC_BUTTONSetH264SecondBitRate  1223
#define IDC_BUTTONGetH264SecondBitRate  1224
#define IDC_BUTTONSetDeNoiseSwitch      1226
#define IDC_BUTTONHVAPI_SoftTriggerCapture 1227
#define IDC_BUTTONSetFaceDataAdv        1228

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        153
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1229
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
